#!/usr/bin/env python3
# Copyright (c) 2026, The Shekyl Foundation
#
# All rights reserved.
# BSD-3-Clause
#
# RT-P7: the ProVerif model of the RPC channel's handshake, hybridXK
# (docs/design/RPC_CHANNEL.md section 4.1), and the runner that checks it.
#
# WHAT IS MODELLED. The token order section 4.1 adopts, in the symbolic
# (Dolev-Yao) model:
#
#     <- s                    the daemon's static bundle (X25519 + ML-KEM)
#     ...
#     -> skem, e, es
#     <- ekem, e, ee
#     -> s, se                payload: grant request
#     <- skem                 payload: grant
#     -> first transport record
#
# WHAT "HYBRID" MEANS HERE, and why one run is not enough. A property is
# hybrid if it survives the loss of either primitive. So the same model is
# run with X25519 broken, with ML-KEM broken, and with both (how a broken
# primitive is modelled is described where the breaks are applied). Each claim in section 4.1 is a row below: a
# variant, a query, and the verdict that claim predicts.
#
# NAMED EDITS. A model that only ever says "true" has not been shown able to
# say anything else. Each edit below removes one token from the pattern, and
# a property that token carries must then FAIL. A named edit whose property
# still holds fails this script: either the edit is not what it says, or the
# property does not depend on what section 4.1 says it does.
#
# WHAT THIS IS NOT. A symbolic model treats X25519, ML-KEM, the AEAD and the
# hash as perfect unless a rule here breaks them. It says the token order
# delivers the stated properties. It says nothing about constant time, about
# the byte encodings, or about Shekyl's code: those are RT-P4, the vectors,
# and RT-W9.
#
# ONE QUERY PER PROVERIF RUN. Every row of the table is its own process with
# its own memory cap. Grouped, the queries of the unbroken model did not fit
# the cap once the second client and injective agreement were added; alone,
# with the one proof-search hint described at HINTED, each does.
#
# Run:  python3 run.py              # every row; exit 1 on any unexpected verdict
#       python3 run.py --list       # the table, without running
#       python3 run.py --keep DIR   # also leave the generated .pv files in DIR
#       python3 run.py --jobs N     # rows in parallel (default: up to 4)
#       python3 run.py --only NAME  # one variant's rows, for working on the model
#
# ONE ProVerif version, here and in CI. The verdicts are pinned to it; this
# script reads the version of the proverif it finds and refuses any other.

import concurrent.futures
import os
import pathlib
import re
import resource
import shutil
import subprocess
import sys
import tempfile
import time

PROVERIF_VERSION = "2.05"

# One row (a variant and one query) is one ProVerif process. A row that
# outlives this is reported as a failure, never skipped: a property nobody
# waited for is not a property that holds.
VARIANT_TIMEOUT_SECONDS = 60 * 60

# ...and one that outgrows this is stopped by the operating system, which
# ProVerif reports as a failure. Without a cap a runaway search takes the
# machine with it; the first version of this model reached 17 GiB in one
# process before it was stopped by hand.
VARIANT_MEMORY_BYTES = 6 * 1024 ** 3

# A row whose peak comes within this fraction of the cap still passes, and is
# called out: it is the row the next change to the model will push over. The
# peak is resident memory and the cap is on address space, which is a little
# larger, so the warning errs early.
MEMORY_WARN_FRACTION = 0.90

PRELUDE = r"""
(* ---- generated by rust/shekyl-rpc-channel/model/run.py; do not edit ---- *)

free c: channel.

type scalar.
type point.
type kemsk.
type kempk.
type kemct.
type seed.
type key.

(* X25519, as a Diffie-Hellman group. *)
const g: point [data].
fun exp(point, scalar): point.
equation forall x: scalar, y: scalar; exp(exp(g, x), y) = exp(exp(g, y), x).

(* ML-KEM, as an IND-CCA KEM: a ciphertext opens only under the secret key. *)
fun kpk(kemsk): kempk.
fun kct(kempk, seed): kemct.
fun kss(kempk, seed): bitstring.
reduc forall sk: kemsk, r: seed; kdecaps(kct(kpk(sk), r), sk) = kss(kpk(sk), r).

(* The handshake's hash and key derivation. *)
fun hinit(bitstring): bitstring.
fun mixh(bitstring, bitstring): bitstring.
fun kdfck(bitstring, bitstring): bitstring.
fun kdfk(bitstring, bitstring): key.
fun kdfh(bitstring, bitstring): bitstring.
fun split1(bitstring): key.
fun split2(bitstring): key.

(* The AEAD, with the handshake hash as associated data. *)
fun aead(key, bitstring, bitstring, bitstring): bitstring.
reduc forall k: key, n: bitstring, ad: bitstring, m: bitstring;
      adec(k, n, ad, aead(k, n, ad, m)) = m.

fun p2b(point): bitstring [data, typeConverter].
fun kpk2b(kempk): bitstring [data, typeConverter].
fun ct2b(kemct): bitstring [data, typeConverter].

const n0: bitstring.
const n1: bitstring.
const n2: bitstring.
const empty: bitstring.
const protocol_name: bitstring.
const prologue: bitstring.
const grant_request: bitstring.
const grant: bitstring.

(* The long-term secrets. Private, so queries can name them. *)
free rs_dh: scalar [private].
free rs_kem: kemsk [private].
free cs_dh: scalar [private].
free cs_kem: kemsk [private].

(* What must stay secret once the handshake is done. *)
free first_request: bitstring [private].
free first_reply: bitstring [private].

(* A second client the daemon has enrolled, whose static secrets the
   attacker holds: a stolen or malicious device. Public names, so the
   attacker has them from the start. What the daemon sends it is public too;
   the honest client's reply is what must stay secret. *)
free ms_dh: scalar.
free ms_kem: kemsk.
free other_reply: bitstring.

(* The daemon's enrolment list: a static key pair and what that client is
   served. One daemon process admits whoever is on it. *)
table enrolled(point, kempk, bitstring).

event DaemonSentM2(point, kempk, bitstring).
event ClientAcceptsDaemon(point, kempk, bitstring).
event ClientSentM3(point, kempk, bitstring).
event DaemonAcceptsClassical(point, kempk, bitstring).
event ClientSentFirstRecord(point, kempk, bitstring).
event DaemonAcceptsHybrid(point, kempk, bitstring).
"""

# HOW A BROKEN PRIMITIVE IS MODELLED. As a primitive whose every shared
# secret is public: with X25519 broken, each Diffie-Hellman result in both
# roles is replaced by one public constant, and likewise each ML-KEM shared
# secret with ML-KEM broken. The keys and ciphertexts still travel as they
# do; they simply protect nothing. That gives the attacker at least what a
# real break would (it need not even see the public keys involved), so a
# property that survives here survives a real break.
#
# Two other ways were tried first and are recorded because each failed for a
# reason worth knowing. Giving the attacker a discrete-log rule beside the
# Diffie-Hellman equation, and a rule recovering a KEM secret key from its
# public key, made ProVerif's search grow without bound: 17 GiB in one
# process within half an hour. Publishing the secret keys instead worked for
# X25519 and still ran out of memory once the daemon's static ML-KEM key
# was among them.
BROKEN = r"""
const broken_dh: point.
const broken_kem: bitstring.
"""

QUERIES = {
    # The three authentication claims are INJECTIVE: each acceptance answers
    # to its own send, so a replayed handshake is not an acceptance. The two
    # client claims name the honest client's keys, because the daemon's list
    # also carries a second client whose keys the attacker holds, and that
    # client is accepted without any honest send, as it should be.
    "daemon_auth": (
        "query rs: point, rk: kempk, h: bitstring;\n"
        "  inj-event(ClientAcceptsDaemon(rs, rk, h)) ==> inj-event(DaemonSentM2(rs, rk, h))."),
    "client_auth_m3": (
        "query h: bitstring;\n"
        "  inj-event(DaemonAcceptsClassical(exp(g, cs_dh), kpk(cs_kem), h))\n"
        "    ==> inj-event(ClientSentM3(exp(g, cs_dh), kpk(cs_kem), h))."),
    "client_auth_record": (
        "query h: bitstring;\n"
        "  inj-event(DaemonAcceptsHybrid(exp(g, cs_dh), kpk(cs_kem), h))\n"
        "    ==> inj-event(ClientSentFirstRecord(exp(g, cs_dh), kpk(cs_kem), h))."),
    "request_secret": "query attacker(first_request).",
    "reply_secret": "query attacker(first_reply).",
    # Both halves of the client's static identity, each its own query.
    "identity_hidden": "query attacker(exp(g, cs_dh)).",
    "identity_hidden_kem": "query attacker(kpk(cs_kem)).",
    "identity_hidden_after_leak": "query attacker(exp(g, cs_dh)) phase 1.",
    "identity_hidden_kem_after_leak": "query attacker(kpk(cs_kem)) phase 1.",
    # Not properties: these must be REACHABLE, or every claim above is true
    # of a protocol that cannot run.
    "reach_client": (
        "query s: point, sk: kempk, h: bitstring; event(ClientSentFirstRecord(s, sk, h))."),
    # The daemon's, for the honest client specifically: with a second client
    # in the attacker's hands, "some client was accepted" proves nothing.
    "reach_daemon": (
        "query h: bitstring; event(DaemonAcceptsHybrid(exp(g, cs_dh), kpk(cs_kem), h))."),
}


def protocol(edits, breaks):
    """The two roles. `edits` is a set of named edits to the token order;
    `breaks` says which primitives' visible secrets are published."""
    no_skem1 = "no_skem_m1" in edits
    no_se = "no_se" in edits
    no_skem4 = "no_skem_m4" in edits

    # --- message 1: skem, e, es ---------------------------------------
    if no_skem1:
        c_m1 = """
  let ck1 = hinit(protocol_name) in
  let h1b = hh0 in"""
        d_m1 = c_m1
        m1_send, m1_recv = "(epub, ekpub, c1)", "(re: point, rek: kempk, c1: bitstring)"
    else:
        c_m1 = """
  new r1: seed;
  let ct1 = kct(rsk, r1) in
  let ss1 = kss(rsk, r1) in
  let h1 = mixh(hh0, ct2b(ct1)) in
  let ck1 = kdfck(hinit(protocol_name), ss1) in
  let h1b = mixh(h1, kdfh(hinit(protocol_name), ss1)) in"""
        d_m1 = """
  let ss1 = kdecaps(ct1, rs_kem) in
  let h1 = mixh(hh0, ct2b(ct1)) in
  let ck1 = kdfck(hinit(protocol_name), ss1) in
  let h1b = mixh(h1, kdfh(hinit(protocol_name), ss1)) in"""
        m1_send = "(ct1, epub, ekpub, c1)"
        m1_recv = "(ct1: kemct, re: point, rek: kempk, c1: bitstring)"

    # --- message 3: s, se ---------------------------------------------
    if no_se:
        c_se = """
  let ck5 = ck4 in
  let c3 = aead(k4, n0x, h8, grant_request) in"""
        d_se = """
  let ck5 = ck4 in
  let (=grant_request) = adec(k4, n0x, h8, c3) in"""
        k_after_s = "k4"
        n_m4_ct = "n1x"
    else:
        c_se = """
  let dh_se = exp(re, cs_dh) in
  let ck5 = kdfck(ck4, p2b(dh_se)) in
  let k5 = kdfk(ck4, p2b(dh_se)) in
  let c3 = aead(k5, n0, h8, grant_request) in"""
        d_se = """
  let dh_se = exp(spub, e_r) in
  let ck5 = kdfck(ck4, p2b(dh_se)) in
  let k5 = kdfk(ck4, p2b(dh_se)) in
  let (=grant_request) = adec(k5, n0, h8, c3) in"""
        k_after_s = "k5"
        n_m4_ct = "n1"

    # --- message 4: skem -----------------------------------------------
    if no_skem4:
        d_m4 = f"""
  let ck6 = ck5 in
  let h11 = h9 in
  let c4 = aead({k_after_s}, {n_m4_ct}, h11, grant) in
  let h12 = mixh(h11, c4) in
  out(c, c4);"""
        c_m4 = f"""
  in(c, c4: bitstring);
  let ck6 = ck5 in
  let h11 = h9 in
  let (=grant) = adec({k_after_s}, {n_m4_ct}, h11, c4) in
  let h12 = mixh(h11, c4) in"""
    else:
        d_m4 = f"""
  new r4: seed;
  let ct4 = kct(skpub, r4) in
  let ss4 = kss(skpub, r4) in
  let cct4 = aead({k_after_s}, {n_m4_ct}, h9, ct2b(ct4)) in
  let h10 = mixh(h9, cct4) in
  let ck6 = kdfck(ck5, ss4) in
  let k6 = kdfk(ck5, ss4) in
  let h11 = mixh(h10, kdfh(ck5, ss4)) in
  let c4 = aead(k6, n0, h11, grant) in
  let h12 = mixh(h11, c4) in
  out(c, (cct4, c4));"""
        c_m4 = f"""
  in(c, (cct4: bitstring, c4: bitstring));
  let ct2b(ct4) = adec({k_after_s}, {n_m4_ct}, h9, cct4) in
  let ss4 = kdecaps(ct4, cs_kem) in
  let h10 = mixh(h9, cct4) in
  let ck6 = kdfck(ck5, ss4) in
  let k6 = kdfk(ck5, ss4) in
  let h11 = mixh(h10, kdfh(ck5, ss4)) in
  let (=grant) = adec(k6, n0, h11, c4) in
  let h12 = mixh(h11, c4) in"""

    # With `se` removed the key of message 3's payload is still k4, which has
    # already sealed three things; give those uses their own nonce names.
    extra_nonces = "const n0x: bitstring.\nconst n1x: bitstring.\n" if no_se else ""

    text = extra_nonces + f"""
let Client(rs: point, rsk: kempk) =
  let hh0 = mixh(mixh(mixh(hinit(protocol_name), prologue), p2b(rs)), kpk2b(rsk)) in
  (* message 1 *){c_m1}
  new e_i: scalar;
  new ek_i: kemsk;
  let epub = exp(g, e_i) in
  let ekpub = kpk(ek_i) in
  let h2 = mixh(mixh(h1b, p2b(epub)), kpk2b(ekpub)) in
  let dh_es = exp(rs, e_i) in
  let ck2 = kdfck(ck1, p2b(dh_es)) in
  let k2 = kdfk(ck1, p2b(dh_es)) in
  let c1 = aead(k2, n0, h2, empty) in
  let h3 = mixh(h2, c1) in
  out(c, {m1_send});
  (* message 2 *)
  in(c, (ct2: kemct, re: point, rek: kempk, c2: bitstring));
  let ss2 = kdecaps(ct2, ek_i) in
  let h4 = mixh(h3, ct2b(ct2)) in
  let ck3 = kdfck(ck2, ss2) in
  let h5 = mixh(mixh(h4, p2b(re)), kpk2b(rek)) in
  let dh_ee = exp(re, e_i) in
  let ck4 = kdfck(ck3, p2b(dh_ee)) in
  let k4 = kdfk(ck3, p2b(dh_ee)) in
  let (=empty) = adec(k4, n0, h5, c2) in
  let h6 = mixh(h5, c2) in
  event ClientAcceptsDaemon(rs, rsk, h6);
  (* message 3 *)
  let spub = exp(g, cs_dh) in
  let skpub = kpk(cs_kem) in
  let cs1 = aead(k4, n1, h6, p2b(spub)) in
  let h7 = mixh(h6, cs1) in
  let cs2 = aead(k4, n2, h7, kpk2b(skpub)) in
  let h8 = mixh(h7, cs2) in{c_se}
  let h9 = mixh(h8, c3) in
  event ClientSentM3(spub, skpub, h9);
  out(c, (cs1, cs2, c3));
  (* message 4 *){c_m4}
  (* first transport record *)
  event ClientSentFirstRecord(spub, skpub, h12);
  out(c, aead(split1(ck6), n0, empty, first_request));
  in(c, reply: bitstring);
  let answer = adec(split2(ck6), n0, empty, reply) in
  0.

let Daemon() =
  let rs = exp(g, rs_dh) in
  let rsk = kpk(rs_kem) in
  let hh0 = mixh(mixh(mixh(hinit(protocol_name), prologue), p2b(rs)), kpk2b(rsk)) in
  (* message 1 *)
  in(c, {m1_recv});{d_m1}
  let h2 = mixh(mixh(h1b, p2b(re)), kpk2b(rek)) in
  let dh_es = exp(re, rs_dh) in
  let ck2 = kdfck(ck1, p2b(dh_es)) in
  let k2 = kdfk(ck1, p2b(dh_es)) in
  let (=empty) = adec(k2, n0, h2, c1) in
  let h3 = mixh(h2, c1) in
  (* message 2 *)
  new r2: seed;
  new e_r: scalar;
  new ek_r: kemsk;
  let ct2 = kct(rek, r2) in
  let ss2 = kss(rek, r2) in
  let h4 = mixh(h3, ct2b(ct2)) in
  let ck3 = kdfck(ck2, ss2) in
  let epub_r = exp(g, e_r) in
  let ekpub_r = kpk(ek_r) in
  let h5 = mixh(mixh(h4, p2b(epub_r)), kpk2b(ekpub_r)) in
  let dh_ee = exp(re, e_r) in
  let ck4 = kdfck(ck3, p2b(dh_ee)) in
  let k4 = kdfk(ck3, p2b(dh_ee)) in
  let c2 = aead(k4, n0, h5, empty) in
  let h6 = mixh(h5, c2) in
  event DaemonSentM2(rs, rsk, h6);
  out(c, (ct2, epub_r, ekpub_r, c2));
  (* message 3 *)
  in(c, (cs1: bitstring, cs2: bitstring, c3: bitstring));
  let p2b(spub) = adec(k4, n1, h6, cs1) in
  let h7 = mixh(h6, cs1) in
  let kpk2b(skpub) = adec(k4, n2, h7, cs2) in
  let h8 = mixh(h7, cs2) in{d_se}
  let h9 = mixh(h8, c3) in
  (* enrolment: only statics on the list are admitted, both halves of one
     entry *)
  get enrolled(=spub, =skpub, reply_for_it) in
  event DaemonAcceptsClassical(spub, skpub, h9);
  (* message 4 *){d_m4}
  (* first transport record: nothing is served before it opens *)
  in(c, record: bitstring);
  (* Any record that opens under the session key is accepted: what the
     daemon learns is that the sender holds the key, not what was sent.
     Requiring the secret `first_request` here would make this event
     unreachable for an attacker whatever the handshake did -- which the
     named edit that removes message 4's skem exposed, by passing. *)
  let request = adec(split1(ck6), n0, empty, record) in
  event DaemonAcceptsHybrid(spub, skpub, h12);
  out(c, aead(split2(ck6), n0, empty, reply_for_it)).
"""
    if "dh" in breaks:
        text, count = re.subn(r"let (dh_\w+) = exp\([^()]*\) in", r"let \1 = broken_dh in", text)
        # es, ee and se, in each role, unless an edit removed se.
        assert count == (4 if "no_se" in edits else 6), count
    if "kem" in breaks:
        text, count = re.subn(r"let (ss\d) = (?:kss|kdecaps)\([^()]*\) in",
                              r"let \1 = broken_kem in", text)
        assert count == 6 - 2 * (("no_skem_m1" in edits) + ("no_skem_m4" in edits)), count
    return text



def main_process(publish_client, leak_daemon_later, replicate):
    publish = "out(c, (exp(g, cs_dh), kpk(cs_kem)));" if publish_client else ""
    leak = "| (phase 1; out(c, (rs_dh, rs_kem)))" if leak_daemon_later else ""
    bang = "!" if replicate else ""
    return f"""
process
  (* Two clients are enrolled: the honest one, and one whose keys the
     attacker holds. *)
  insert enrolled(exp(g, cs_dh), kpk(cs_kem), first_reply);
  insert enrolled(exp(g, ms_dh), kpk(ms_kem), other_reply);
  (* The daemon's bundle is not a secret: every enrolled client holds it. *)
  out(c, (exp(g, rs_dh), kpk(rs_kem)));
  {publish}
  ( ({bang}Client(exp(g, rs_dh), kpk(rs_kem)))
  | ({bang}Daemon())
  {leak} )
"""


# A variant: (name, breaks, edits, publish_client, leak_daemon_later, {query: expected}).
# Expected is True for "the property holds", False for "ProVerif finds an
# attack". For the two reach_* queries the sense is inverted by ProVerif
# itself: "not event(...) is false" means reachable, which is what is wanted.
HOLDS, ATTACK, REACHABLE = "holds", "attack", "reachable"

VARIANTS = [
    # Sanity first: one session of each role runs to completion. Bounded,
    # because finding an honest trace through unbounded sessions is the most
    # expensive thing ProVerif is asked here, and one session is all it takes
    # to show the claims below are not about a protocol that cannot run.
    ("reachable", (), (), True, False, {
        "reach_client": REACHABLE, "reach_daemon": REACHABLE}),
    ("baseline", (), (), True, False, {
        "daemon_auth": HOLDS, "client_auth_m3": HOLDS, "client_auth_record": HOLDS,
        "request_secret": HOLDS, "reply_secret": HOLDS}),
    # Section 4.1: daemon authentication is hybrid; client authentication is
    # classical at message 3 and hybrid at the first record.
    ("x25519_broken", ("dh",), (), True, False, {
        "daemon_auth": HOLDS, "client_auth_m3": ATTACK, "client_auth_record": HOLDS,
        "request_secret": HOLDS, "reply_secret": HOLDS}),
    ("mlkem_broken", ("kem",), (), True, False, {
        "daemon_auth": HOLDS, "client_auth_m3": HOLDS, "client_auth_record": HOLDS,
        "request_secret": HOLDS, "reply_secret": HOLDS}),
    # Control: with both broken nothing should hold. If it did, the two
    # breaks would be shown to have no teeth.
    ("both_broken", ("dh", "kem"), (), True, False, {
        "daemon_auth": ATTACK, "client_auth_record": ATTACK, "request_secret": ATTACK}),
    # Section 4.2: the client's identity is hidden from the path, under
    # either break, and stays hidden if the daemon's key leaks later.
    ("identity", (), (), False, False, {
        "identity_hidden": HOLDS, "identity_hidden_kem": HOLDS}),
    ("identity_x25519_broken", ("dh",), (), False, False, {
        "identity_hidden": HOLDS, "identity_hidden_kem": HOLDS}),
    ("identity_mlkem_broken", ("kem",), (), False, False, {
        "identity_hidden": HOLDS, "identity_hidden_kem": HOLDS}),
    ("identity_daemon_key_leaks_later", (), (), False, True, {
        "identity_hidden_after_leak": HOLDS, "identity_hidden_kem_after_leak": HOLDS}),
    # Named edits. Each removes one token; the property it carries must fail.
    ("edit_no_skem_in_message_1", ("dh",), ("no_skem_m1",), True, False, {
        "daemon_auth": ATTACK}),
    ("edit_no_se_in_message_3", (), ("no_se",), True, False, {
        "client_auth_m3": ATTACK}),
    ("edit_no_skem_in_message_4", ("dh",), ("no_skem_m4",), True, False, {
        "client_auth_record": ATTACK}),
]

BOUNDED = {"reachable"}

# A PROOF-SEARCH HINT, and where it is used. ProVerif proves a property by
# saturating a set of clauses, and which hypothesis it resolves on next is a
# choice that decides whether saturation ends. Left to its default, two
# variants grow past the memory cap once the second client is enrolled: the
# unbroken model on each of its three authentication queries, and the
# later-key-leak variant on both of its queries. An attacker who holds one
# enrolled key can finish handshakes, and every Diffie-Hellman value it
# might have fed them becomes a case. The hint tells ProVerif not to resolve
# on "the attacker knows exp(x, y)" during saturation, and to try it a
# bounded number of times when checking the goal.
#
# A hint changes the search, never the model: the clauses are the same and
# resolution is sound whatever is selected. What it can cost is precision
# (ProVerif's manual, section 6.7.2: such declarations "help the saturation
# procedure to terminate but they may lower the precision"). So a verdict of
# "true" under the hint is a proof, and the price shows up as "cannot be
# proved" -- which this script counts as a failure. That price is real: with
# the hint, the variants that expect an attack report "cannot be proved"
# instead of finding it. They do not need the hint and do not get it.
NOUNIF_DH = "nounif x: point, y: scalar; attacker(exp( *x, *y)) [ignoreAFewTimes].\n"
HINTED = {"baseline", "identity_daemon_key_leaks_later"}


def source(name, breaks, edits, publish_client, leak_daemon_later, queries):
    replicate = name not in BOUNDED
    parts = [PRELUDE, BROKEN]
    if name in HINTED:
        parts.append(NOUNIF_DH)
    parts.extend(QUERIES[q] + "\n" for q in queries)
    parts.append(protocol(set(edits), set(breaks)))
    parts.append(main_process(publish_client, leak_daemon_later, replicate))
    return "\n".join(parts)


def proverif_version(binary):
    out = subprocess.run([binary, "-help"], capture_output=True, text=True)
    match = re.search(r"Proverif (\d+\.\d+[\w.]*)", out.stdout + out.stderr)
    return match.group(1).rstrip(".") if match else None


def verdicts(output):
    """ProVerif's RESULT lines, in order, as holds / attack / replay-only / unknown.

    When an injective query fails, ProVerif adds a second, parenthesised line
    for the same query saying whether the non-injective form fails too
    ("even ...") or holds ("but ..."). It is not another query. "but" means
    the only attack is a replay, which no expectation here accepts: an
    expected attack is one on the correspondence itself.
    """
    found = []
    for line in output.splitlines():
        if not line.startswith("RESULT"):
            continue
        if line.startswith("RESULT ("):
            if found and not line.startswith("RESULT (even "):
                found[-1] = "replay-only"
            continue
        if "cannot be proved" in line:
            found.append("unknown")
        elif line.rstrip().endswith("is true."):
            found.append("holds")
        elif line.rstrip().endswith("is false."):
            found.append("attack")
        else:
            found.append("unknown")
    return found


def _cap_memory():
    resource.setrlimit(resource.RLIMIT_AS, (VARIANT_MEMORY_BYTES, VARIANT_MEMORY_BYTES))


def _report_as_done(results):
    for result in results:
        name, query, _want, returncode, _output, seconds, peak_mib = result
        state = "timed out" if returncode is None else f"exit {returncode}"
        print(f"..   {name}: {query}: finished, {state}, {seconds:.0f} s, peak {peak_mib} MiB",
              flush=True)
        yield result


def main():
    args = sys.argv[1:]
    if "--list" in args:
        for name, breaks, edits, publish, leak, expected in VARIANTS:
            print(name, "breaks=" + (",".join(breaks) or "none"),
                  "edits=" + (",".join(edits) or "none"))
            for query, want in expected.items():
                print(f"    {query}: {want}")
        return 0

    binary = shutil.which("proverif")
    if binary is None:
        print("proverif is not on PATH: the model was not run", file=sys.stderr)
        return 2
    version = proverif_version(binary)
    if version != PROVERIF_VERSION:
        print(f"proverif is version {version!r}; the verdicts are pinned to "
              f"{PROVERIF_VERSION!r}. Install that version (opam install "
              f"proverif.{PROVERIF_VERSION}) or re-derive every verdict and move the pin.",
              file=sys.stderr)
        return 2

    keep = pathlib.Path(args[args.index("--keep") + 1]) if "--keep" in args else None
    if keep is not None:
        keep.mkdir(parents=True, exist_ok=True)

    # Capped by default: each row may take VARIANT_MEMORY_BYTES.
    jobs = int(args[args.index("--jobs") + 1]) if "--jobs" in args else min(os.cpu_count() or 1, 4)
    only = args[args.index("--only") + 1] if "--only" in args else None
    variants = [v for v in VARIANTS if only in (None, v[0])]
    if not variants:
        print(f"no variant is named {only!r}", file=sys.stderr)
        return 2

    def run_row(row, work):
        (name, breaks, edits, publish, leak, expected), query = row
        path = work / f"{name}.{query}.pv"
        path.write_text(source(name, breaks, edits, publish, leak, [query]), encoding="utf-8")
        started = time.monotonic()
        # Output goes to a file, not a pipe, so the child can be reaped with
        # wait4 and its own peak memory read: the cap is only a good cap if
        # somebody can see how close each row runs to it.
        with open(work / f"{name}.{query}.out", "w+", encoding="utf-8") as sink:
            child = subprocess.Popen([binary, str(path)], stdout=sink, stderr=subprocess.STDOUT,
                                     preexec_fn=_cap_memory)
            deadline = started + VARIANT_TIMEOUT_SECONDS
            while True:
                pid, status, usage = os.wait4(child.pid, os.WNOHANG)
                if pid:
                    break
                if time.monotonic() > deadline:
                    child.kill()
                    os.wait4(child.pid, 0)
                    return name, query, expected[query], None, "", time.monotonic() - started, 0
                time.sleep(0.2)
            child.returncode = os.waitstatus_to_exitcode(status)
            sink.seek(0)
            output = sink.read()
        return (name, query, expected[query], child.returncode, output,
                time.monotonic() - started, usage.ru_maxrss // 1024)

    rows = [(variant, query) for variant in variants for query in variant[5]]
    failures = 0
    checked = 0
    near_cap = []
    warn_mib = MEMORY_WARN_FRACTION * VARIANT_MEMORY_BYTES / 1024 ** 2
    with tempfile.TemporaryDirectory() as tmp:
        work = keep or pathlib.Path(tmp)
        with concurrent.futures.ThreadPoolExecutor(max_workers=max(1, jobs)) as pool:
            pending = [pool.submit(run_row, row, work) for row in rows]
            results = (f.result() for f in concurrent.futures.as_completed(pending))
            # Reported as each row finishes: the slow ones take minutes, and
            # a silent job looks like a hung one.
            results = list(_report_as_done(results))
        order = {(row[0][0], row[1]): index for index, row in enumerate(rows)}
        results.sort(key=lambda r: order[(r[0], r[1])])
        for name, query, want, returncode, output, seconds, peak_mib in results:
            if returncode is None:
                failures += 1
                print(f"FAIL {name}: {query}: no verdict within {VARIANT_TIMEOUT_SECONDS} s",
                      file=sys.stderr)
                continue
            if peak_mib > warn_mib:
                near_cap.append((name, query, peak_mib))
            got = verdicts(output)
            if returncode != 0 or len(got) != 1:
                failures += 1
                print(f"FAIL {name}: {query}: proverif exit {returncode}, "
                      f"{len(got)} verdict(s) for one query", file=sys.stderr)
                for line in output.strip().splitlines()[-6:]:
                    print("     " + line, file=sys.stderr)
                continue
            verdict = got[0]
            # A reachability query is "not event(...)": false means reachable.
            ok = (verdict == "attack") if want == REACHABLE else (verdict == want)
            checked += 1
            if ok:
                print(f"ok   {name}: {query} -> {want}  ({seconds:.0f} s, peak {peak_mib} MiB)")
            else:
                failures += 1
                print(f"FAIL {name}: {query} expected {want}, ProVerif says {verdict}",
                      file=sys.stderr)
    if checked == 0:
        print("no verdict was checked: the model did not run", file=sys.stderr)
        return 2
    cap_mib = VARIANT_MEMORY_BYTES // 1024 ** 2
    for name, query, peak_mib in near_cap:
        print(f"WARN {name}: {query}: peak {peak_mib} MiB is over "
              f"{MEMORY_WARN_FRACTION:.0%} of the {cap_mib} MiB cap", file=sys.stderr)
        # GitHub Actions shows this on the run's summary page.
        print(f"::warning title=RT-P7 model near its memory cap::{name}: {query} peaked at "
              f"{peak_mib} MiB of {cap_mib} MiB")
    print(f"{checked} verdict(s) checked, {failures} unexpected, "
          f"{len(near_cap)} within {1 - MEMORY_WARN_FRACTION:.0%} of the memory cap")
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
