// Copyright (c) 2025-2026, The Shekyl Foundation
//
// All rights reserved.
// BSD-3-Clause

//! Emit `CONSENSUS_CONSTANTS_DIGEST` — the digest of the canonical form of
//! the integer constant authorities under `config/`
//! (`consensus_constants.json` and `economics_params.json`) — for
//! `src/consensus_digest.rs` (`docs/design/CLIENT_VERSION_CONSTANTS_VALIDATION.md`
//! §3.3, §3.4, §3.12; `VC-1`).
//!
//! Computed **once, here**, because every RPC party (`shekyl-daemon-rpc`,
//! `shekyl-engine-core`, `shekyl-rpc-client`) already depends on this crate
//! and the digest is a wire-contract fact that sits beside
//! `CORE_RPC_VERSION`. The consensus-constant and economics generators
//! elsewhere in the workspace read the same JSON for their own values and do
//! not compute this (`VC-D4`); neither does
//! `cmake/generate_consensus_constants.py`, because nothing in C++ consumes
//! it (`VC-D9`).
//!
//! The canonicalisation rules live in `build_support/consensus_canonical.rs`,
//! which this build script and the crate's tests both include — one
//! definition, two readers.

#[path = "build_support/consensus_canonical.rs"]
mod consensus_canonical;

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("missing CARGO_MANIFEST_DIR"));
    // shekyl-rpc-types lives at rust/shekyl-rpc-types; the JSON authorities
    // are two levels up under config/.
    let repo_root = manifest_dir
        .parent()
        .expect("workspace/rust path expected")
        .parent()
        .expect("workspace root path expected")
        .to_path_buf();

    println!(
        "cargo:rerun-if-changed={}",
        manifest_dir
            .join("build_support")
            .join("consensus_canonical.rs")
            .display()
    );
    println!("cargo:rerun-if-changed=build.rs");

    let mut contents = Vec::with_capacity(consensus_canonical::CANONICAL_FILES.len());
    for file in consensus_canonical::CANONICAL_FILES {
        let path = repo_root.join(file);
        println!("cargo:rerun-if-changed={}", path.display());
        let raw = fs::read_to_string(&path)
            .unwrap_or_else(|e| panic!("failed to read {}: {e}", path.display()));
        contents.push(raw);
    }
    let pairs: Vec<(&str, &str)> = consensus_canonical::CANONICAL_FILES
        .iter()
        .copied()
        .zip(contents.iter().map(String::as_str))
        .collect();
    let canonical = consensus_canonical::canonical_form(&pairs).unwrap_or_else(|e| panic!("{e}"));
    let digest = consensus_canonical::digest_hex(&canonical);

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("missing OUT_DIR"));
    let out_file = out_dir.join("consensus_constants_digest.rs");

    // `{canonical:?}` renders the text as a valid Rust string literal.
    let output = format!(
        "// @generated by build.rs from config/consensus_constants.json and\n\
         // config/economics_params.json — do not edit.\n\
         //\n\
         // The canonical form (CLIENT_VERSION_CONSTANTS_VALIDATION.md §3.3, §3.12)\n\
         // and its SHA-256, computed once for every RPC party in the workspace.\n\
         pub const CONSENSUS_CONSTANTS_DIGEST: &str = \"{digest}\";\n\
         pub const CONSENSUS_CONSTANTS_CANONICAL: &str = {canonical:?};\n"
    );

    fs::write(&out_file, output).expect("failed writing generated consensus constants digest");
}
