// Copyright (c) 2025-2026, The Shekyl Foundation
//
// All rights reserved.
// BSD-3-Clause

//! Emit `CONSENSUS_CONSTANTS_DIGEST` — the digest of the canonical form of
//! `config/consensus_constants.json` — for `src/consensus_digest.rs`
//! (`docs/design/CLIENT_VERSION_CONSTANTS_VALIDATION.md` §3.3–§3.4, `VC-1`).
//!
//! Computed **once, here**, because every RPC party (`shekyl-daemon-rpc`,
//! `shekyl-engine-core`, `shekyl-rpc-client`) already depends on this crate
//! and the digest is a wire-contract fact that sits beside
//! `CORE_RPC_VERSION`. The seven consensus-constant generators elsewhere in
//! the workspace read the same JSON for their own values and do not compute
//! this (`VC-D4`); neither does `cmake/generate_consensus_constants.py`,
//! because nothing in C++ consumes it (`VC-D9`).
//!
//! The canonicalisation rules live in `build_support/consensus_canonical.rs`,
//! which this build script and the crate's tests both include — one
//! definition, two readers.

#[path = "build_support/consensus_canonical.rs"]
mod consensus_canonical;

use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("missing CARGO_MANIFEST_DIR"));
    // shekyl-rpc-types lives at rust/shekyl-rpc-types; the JSON authority is
    // two levels up at config/.
    let config_path = manifest_dir
        .parent()
        .expect("workspace/rust path expected")
        .parent()
        .expect("workspace root path expected")
        .join("config")
        .join("consensus_constants.json");

    println!("cargo:rerun-if-changed={}", config_path.display());
    println!(
        "cargo:rerun-if-changed={}",
        manifest_dir
            .join("build_support")
            .join("consensus_canonical.rs")
            .display()
    );
    println!("cargo:rerun-if-changed=build.rs");

    let raw = fs::read_to_string(&config_path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", config_path.display()));
    let canonical = consensus_canonical::canonical_form(&raw)
        .unwrap_or_else(|e| panic!("{}: {e}", config_path.display()));
    let digest = consensus_canonical::digest_hex(&canonical);

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("missing OUT_DIR"));
    let out_file = out_dir.join("consensus_constants_digest.rs");

    // `{canonical:?}` renders the text as a valid Rust string literal.
    let output = format!(
        "// @generated by build.rs from config/consensus_constants.json — do not edit.\n\
         //\n\
         // The canonical form (CLIENT_VERSION_CONSTANTS_VALIDATION.md §3.3) and its\n\
         // SHA-256, computed once for every RPC party in the workspace.\n\
         pub const CONSENSUS_CONSTANTS_DIGEST: &str = \"{digest}\";\n\
         pub const CONSENSUS_CONSTANTS_CANONICAL: &str = {canonical:?};\n"
    );

    fs::write(&out_file, output).expect("failed writing generated consensus constants digest");
}
