//! Generate consensus-constant Rust mirrors from the JSON authority at
//! `config/consensus_constants.json`. The same JSON drives the C++
//! header generator at `cmake/generate_consensus_constants.py`, so the
//! two languages cannot drift. Bug 3 of the 2026-05-05 FFI
//! constant-drift audit motivated the JSON authority; see
//! `docs/audit_trail/2026-05-ffi-constant-drift-audit.md`.
//!
//! Mirrors the pattern of `rust/shekyl-staking/build.rs`
//! (economics-params JSON → generated `tier_params_generated.rs`).
//! The `multisig` module `include!`s the emitted file; sentinel
//! `const_assert!`s at the consumption sites pin meaning across
//! changes.

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::PathBuf;

fn get_u64(map: &BTreeMap<String, serde_json::Value>, key: &str) -> u64 {
    map.get(key)
        .and_then(serde_json::Value::as_u64)
        .unwrap_or_else(|| {
            panic!("missing or invalid u64 key in consensus_constants.json: {key}")
        })
}

fn main() {
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("missing CARGO_MANIFEST_DIR"));
    // shekyl-engine-core lives at rust/shekyl-engine-core; the
    // workspace JSON authority is two levels up at config/.
    let config_path = manifest_dir
        .parent()
        .expect("workspace/rust path expected")
        .parent()
        .expect("workspace root path expected")
        .join("config")
        .join("consensus_constants.json");

    println!("cargo:rerun-if-changed={}", config_path.display());

    let raw = fs::read_to_string(&config_path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", config_path.display()));
    let map: BTreeMap<String, serde_json::Value> =
        serde_json::from_str(&raw).expect("invalid JSON in consensus_constants.json");

    let min_age = get_u64(&map, "fcmp_reference_block_min_age");
    let max_age = get_u64(&map, "fcmp_reference_block_max_age");
    let rct_type = get_u64(&map, "rct_type_fcmp_plus_plus_pqc");
    assert!(
        rct_type <= u64::from(u8::MAX),
        "rct_type_fcmp_plus_plus_pqc must fit in u8 (got {rct_type})"
    );

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("missing OUT_DIR"));
    let out_file = out_dir.join("consensus_constants_generated.rs");

    let output = format!(
        "// @generated by build.rs from config/consensus_constants.json — do not edit.\n\
         //\n\
         // Single source of truth: `config/consensus_constants.json`. The C++\n\
         // header at `shekyl/consensus_constants_generated.h` is emitted from\n\
         // the same JSON by `cmake/generate_consensus_constants.py`.\n\
         pub const FCMP_REFERENCE_BLOCK_MIN_AGE: u64 = {min_age};\n\
         pub const FCMP_REFERENCE_BLOCK_MAX_AGE: u64 = {max_age};\n\
         pub const RCT_TYPE_FCMP_PLUS_PLUS_PQC: u8 = {rct_type};\n",
    );

    fs::write(&out_file, output).expect("failed writing generated consensus constants");
}
