# Configuration for shekyl-core
# Syntax: any command line option may be specified as 'clioptionname=value'.
#         Boolean options such as 'no-igd' are specified as 'no-igd=1'.
# See 'shekyl-core --help' for all available options.

data-dir=/var/lib/shekyl-core
log-file=/var/log/shekyl-core/shekyl-core.log
log-level=0
