// Copyright (c) 2025-2026, The Shekyl Foundation
//
// All rights reserved.
// BSD-3-Clause

//! Monetary amounts as a checked-only newtype.
//!
//! [`AtomicUnits`] wraps a `u64` of **atomic units** (the chain's smallest
//! denomination; `10^9` atomic units = 1 SKL — see
//! `docs/completed/ATOMIC_UNITS_NEWTYPE.md`). It replaces raw `u64` on the
//! wallet's money path to remove two inherited bug classes by construction:
//!
//! 1. **Silent wrap.** There are no `Add`/`Sub`/`Mul`/`Div` operator impls and
//!    no `saturating_*`; arithmetic is *checked-only*
//!    ([`Self::checked_add`], [`Self::checked_sub`], [`Self::checked_sum`]).
//!    `a + b` does not compile, so a local accounting bug cannot silently wrap
//!    (or saturate) on a money path. This is a priority-1 (security) property
//!    per `00-mission.mdc`.
//! 2. **Unit confusion.** [`AtomicUnits`] is *always* atomic integer units.
//!    [`Display`](core::fmt::Display)/[`Debug`](core::fmt::Debug) render the
//!    raw integer with an `au` marker, never SKL, so a log line cannot be
//!    misread as a SKL figure. SKL formatting is available only through the
//!    explicit, single-sourced [`Self::to_skl_string`] /
//!    [`Self::from_skl_str`].
//!
//! ## Boundaries
//!
//! The inner `u64` is private. Conversion happens only through the named
//! [`Self::from_raw`] / [`Self::to_raw`] (no blanket `From<u64>`/`Into<u64>`),
//! so the conversion call sites are the greppable edge set that bounds the
//! migration. `#[serde(transparent)]` + `#[repr(transparent)]` make the type
//! wire- and ABI-identical to the `u64` it replaces, so the swap requires no
//! serialized-format version bump.
//!
//! ## Denomination source
//!
//! [`ATOMIC_UNITS_PER_SKL`] and [`DISPLAY_DECIMAL_POINT`] are generated by
//! `build.rs` from `config/economics_params.json` (`coin` /
//! `display_decimal_point`), the same JSON the other economics build scripts
//! read. There is no hardcoded `1_000_000_000` literal in the library code
//! (test assertions in `src/tests.rs` hardcode expected values, as tests
//! should).

use std::fmt;

use serde::{Deserialize, Serialize};
use zeroize::Zeroize;

// `ATOMIC_UNITS_PER_SKL: u64` and `DISPLAY_DECIMAL_POINT: u8`, generated from
// `config/economics_params.json` by `build.rs`.
include!(concat!(env!("OUT_DIR"), "/units_generated.rs"));

// Defense-in-depth mirror of the build-time drift guard: the denomination is
// coherent only when `coin == 10^display_decimal_point`. `build.rs` already
// asserts this against the JSON; this `const _` re-asserts it against the
// generated constants so a hand-edit to the generated file can't slip through.
#[allow(clippy::cast_lossless)] // const context: `u32::from` is not const-callable here.
const _: () = assert!(ATOMIC_UNITS_PER_SKL == 10u64.pow(DISPLAY_DECIMAL_POINT as u32));

/// A monetary amount in atomic units.
///
/// See the [crate-level docs](crate) for the checked-only arithmetic and
/// unit-marker display rationale. Constructed from raw `u64` at edges via
/// [`Self::from_raw`]; aggregated with [`Self::checked_add`] /
/// [`Self::checked_sum`]; compared with the derived [`Ord`]/[`Eq`].
///
/// `Copy` mirrors today's `u64` ergonomics. The recorded tradeoff is that a
/// `Copy` amount can leave un-zeroized copies — identical to the raw-`u64`
/// posture this replaces. Secret hygiene stays at the container level
/// (`OutputClaim` is `ZeroizeOnDrop`; this type is [`Zeroize`] so that keeps
/// compiling).
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Default, Zeroize, Serialize, Deserialize)]
#[serde(transparent)]
#[repr(transparent)]
pub struct AtomicUnits(u64);

impl AtomicUnits {
    /// The zero amount. The additive identity for [`Self::checked_sum`].
    pub const ZERO: Self = AtomicUnits(0);

    /// Wrap a raw `u64` of atomic units.
    ///
    /// An *edge* constructor: use it only where amounts cross into Shekyl's
    /// typed domain (FFI, the `shekyl-oxide` fork, deserialization helpers).
    /// Inside the domain, build amounts from existing [`AtomicUnits`] via the
    /// checked arithmetic so no bare `u64` re-enters as an amount.
    pub const fn from_raw(atomic_units: u64) -> Self {
        AtomicUnits(atomic_units)
    }

    /// Unwrap to the raw `u64` of atomic units.
    ///
    /// An *edge* accessor: use it only where amounts cross back out to a
    /// `u64`-typed boundary (a `Commitment` amount, an oxide-tx fee, a
    /// `to_le_bytes` hash input, an FFI out-parameter).
    pub const fn to_raw(self) -> u64 {
        self.0
    }

    /// Checked addition. `None` on `u64` overflow.
    ///
    /// The `None` arm is a real overflow on the money path and must be
    /// surfaced as an error, never defaulted to [`Self::ZERO`].
    pub const fn checked_add(self, rhs: Self) -> Option<Self> {
        match self.0.checked_add(rhs.0) {
            Some(v) => Some(AtomicUnits(v)),
            None => None,
        }
    }

    /// Checked subtraction. `None` on underflow (`self < rhs`).
    ///
    /// On invariant-protected sites (e.g. `dust = pool - distributed` where
    /// `pool >= distributed`), `None` means a real bug and must be surfaced
    /// as an error/assertion, never defaulted to [`Self::ZERO`].
    pub const fn checked_sub(self, rhs: Self) -> Option<Self> {
        match self.0.checked_sub(rhs.0) {
            Some(v) => Some(AtomicUnits(v)),
            None => None,
        }
    }

    /// Sum an iterator of amounts. `None` if the running total overflows
    /// `u64`. Returns [`Self::ZERO`] for an empty iterator.
    pub fn checked_sum(iter: impl IntoIterator<Item = Self>) -> Option<Self> {
        let mut acc = Self::ZERO;
        for item in iter {
            acc = acc.checked_add(item)?;
        }
        Some(acc)
    }

    /// Whether this is the zero amount.
    pub const fn is_zero(self) -> bool {
        self.0 == 0
    }

    /// Format as a fixed-precision SKL decimal string
    /// (`DISPLAY_DECIMAL_POINT` fractional digits, e.g. `12.345000000`).
    ///
    /// Exact integer formatting — no `f64`. Fixed-width fractional output
    /// makes the round-trip with [`Self::from_skl_str`] total and CLI output
    /// deterministic.
    pub fn to_skl_string(self) -> String {
        let whole = self.0 / ATOMIC_UNITS_PER_SKL;
        let frac = self.0 % ATOMIC_UNITS_PER_SKL;
        let width = usize::from(DISPLAY_DECIMAL_POINT);
        format!("{whole}.{frac:0width$}")
    }

    /// Parse a SKL decimal string into atomic units.
    ///
    /// The user-facing money parser. Strict by design (truncating or wrapping
    /// money is corruption):
    ///
    /// - requires at least one integer digit (`".5"` and `"."` are rejected);
    /// - rejects more than `DISPLAY_DECIMAL_POINT` fractional digits rather
    ///   than truncating;
    /// - rejects empty input, signs, whitespace, multiple `.`, and any
    ///   non-digit character;
    /// - errors when the value exceeds `u64::MAX` atomic units.
    pub fn from_skl_str(s: &str) -> Result<Self, ParseAmountError> {
        if s.is_empty() {
            return Err(ParseAmountError::Empty);
        }

        let mut parts = s.split('.');
        let int_str = parts.next().unwrap_or("");
        let frac_str = parts.next().unwrap_or("");
        if parts.next().is_some() {
            return Err(ParseAmountError::MultipleDots);
        }

        if int_str.is_empty() || !int_str.bytes().all(|b| b.is_ascii_digit()) {
            return Err(ParseAmountError::Malformed);
        }
        if !frac_str.bytes().all(|b| b.is_ascii_digit()) {
            return Err(ParseAmountError::Malformed);
        }
        if frac_str.len() > usize::from(DISPLAY_DECIMAL_POINT) {
            return Err(ParseAmountError::TooManyDecimals);
        }

        let whole: u64 = int_str.parse().map_err(|_| ParseAmountError::Overflow)?;
        let whole_atomic = whole
            .checked_mul(ATOMIC_UNITS_PER_SKL)
            .ok_or(ParseAmountError::Overflow)?;

        let frac_atomic = if frac_str.is_empty() {
            0u64
        } else {
            let width = usize::from(DISPLAY_DECIMAL_POINT);
            let mut padded = String::with_capacity(width);
            padded.push_str(frac_str);
            while padded.len() < width {
                padded.push('0');
            }
            // `padded` is all digits, width == DISPLAY_DECIMAL_POINT, so the
            // value is < ATOMIC_UNITS_PER_SKL <= u64::MAX; parse is infallible.
            padded.parse().map_err(|_| ParseAmountError::Malformed)?
        };

        let total = whole_atomic
            .checked_add(frac_atomic)
            .ok_or(ParseAmountError::Overflow)?;
        Ok(AtomicUnits(total))
    }
}

impl fmt::Display for AtomicUnits {
    /// Renders raw atomic units with an `au` marker, never SKL. Use
    /// [`Self::to_skl_string`] for SKL display.
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{} au", self.0)
    }
}

impl fmt::Debug for AtomicUnits {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "AtomicUnits({} au)", self.0)
    }
}

/// Error from [`AtomicUnits::from_skl_str`].
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum ParseAmountError {
    /// Empty input.
    Empty,
    /// More than one `.` separator.
    MultipleDots,
    /// More fractional digits than [`DISPLAY_DECIMAL_POINT`] allows. Rejected
    /// rather than truncated — truncating money is corruption.
    TooManyDecimals,
    /// The value exceeds `u64::MAX` atomic units.
    Overflow,
    /// Missing integer digits, a sign, whitespace, or other non-digit input.
    Malformed,
}

impl fmt::Display for ParseAmountError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let msg = match self {
            ParseAmountError::Empty => "empty amount string",
            ParseAmountError::MultipleDots => "amount has more than one decimal point",
            ParseAmountError::TooManyDecimals => "amount has more fractional digits than allowed",
            ParseAmountError::Overflow => "amount exceeds the maximum representable value",
            ParseAmountError::Malformed => "malformed amount string",
        };
        f.write_str(msg)
    }
}

impl std::error::Error for ParseAmountError {}

#[cfg(test)]
mod tests;
