#!/usr/bin/env bash
#
# Copyright (c) 2025-2026, The Shekyl Foundation
# All rights reserved. BSD-3-Clause.
# (Builds against a local XMRig clone (GPLv3) via XMRIG_DIR; XMRig is not vendored
#  or distributed here. The built binary is GPLv3 by linkage and is not distributed.)
# Build the XMRig-ceiling hash-core differential harness (Phase 0, RANDOMX_V2_MINING_ASYMMETRY §3.2).
#
# Links XMRig 6.26.0's ACTUAL RandomX sources (so we test the miner an adversary runs)
# against a minimal honest support layer, and checks its rx/2 hashes against Shekyl's
# canonical pins. Not CI-wired: it needs a local XMRig clone, so it is a documented,
# reproducible reference harness rather than a gate that fires in CI without that clone.
#
# Prereqs:
#   - XMRig cloned at $XMRIG_DIR, pinned to b2ca7248 (v6.26.0).
#   - parity_corpus.dat generated by `gen-parity-corpus` (or reuse a build's copy);
#     its SHA-256 must equal PARITY_CORPUS_FILE_SHA256 (parity_corpus.rs) so it carries
#     the committed CANONICAL_RANDOM_HASHES.
#
# Usage:
#   XMRIG_DIR=/path/to/xmrig ./build.sh
#   ./xmrig_parity --rx0                       # build-faithfulness self-check (v1 vector)
#   ./xmrig_parity --kat                        # single v2 KAT, light-JIT
#   ./xmrig_parity --kat-full                   # single v2 KAT, full-dataset (the adversary mode)
#   ./xmrig_parity /path/to/parity_corpus.dat   # full 1024-vector full-dataset differential
set -euo pipefail

XMRIG_DIR="${XMRIG_DIR:-/home/torvaldsl/shekyl/xmrig}"
X="$XMRIG_DIR/src/crypto/randomx"
A="$XMRIG_DIR/src/3rdparty/argon2"
here="$(cd "$(dirname "$0")" && pwd)"
out="${OUT_DIR:-$here/build}"
mkdir -p "$out"; cd "$out"

PIN="b2ca7248"
have="$(git -C "$XMRIG_DIR" rev-parse --short HEAD 2>/dev/null || echo '?')"
[ "$have" = "$PIN" ] || echo "WARNING: XMRig HEAD is $have, expected pin $PIN — re-pin or ceiling numbers are void."

INC="-I$XMRIG_DIR/src -I$X"
# XMRIG_FEATURE_ASM is REQUIRED: without it jit_compiler.hpp selects the fallback JIT,
# which throws "JIT compilation is not supported" — and XMRig's v2 tweaks (AES/CFROUND/
# COMMITMENT) live only in the JIT (its interpreter/light path is v2-incomplete).
DEF="-DHAVE_POSIX_MEMALIGN -DXMRIG_FEATURE_ASM"

echo "== compiling XMRig RandomX (x86-64 JIT, software-AES path) =="
gcc -O2 $DEF $INC -c "$X/blake2/blake2b.c" -o blake2b.o
gcc -O2 $DEF $INC -c "$X/reciprocal.c"     -o reciprocal.o
for cc in aes_hash allocator blake2_generator bytecode_machine dataset instructions_portable \
          randomx soft_aes superscalar virtual_machine virtual_memory \
          vm_compiled_light vm_compiled vm_interpreted_light vm_interpreted jit_compiler_x86; do
  g++ -O2 -std=c++17 $DEF $INC -c "$X/$cc.cpp" -o "$cc.o"
done
gcc -O2 $DEF $INC -c "$X/jit_compiler_x86_static.S" -o jit_compiler_x86_static.o
ar rcs libxmrig_randomx.a ./*.o

echo "== compiling Argon2 (generic arch; output-identical to the SIMD variants) =="
AINC="-I$XMRIG_DIR/src -I$A/include -I$A/lib"
for c in lib/argon2.c lib/core.c lib/encoding.c lib/genkat.c lib/impl-select.c \
         lib/blake2/blake2.c arch/generic/lib/argon2-arch.c; do
  gcc -O2 -std=c99 -D_GNU_SOURCE $AINC -c "$A/$c" -o "argon2_$(echo "$c" | tr '/' '_' | sed 's/\.c$/.o/')"
done
ar rcs libargon2.a argon2_*.o

echo "== compiling support layer + harness =="
g++ -O2 -std=c++17 -I"$XMRIG_DIR/src" -c "$here/support.cpp"      -o support.o
g++ -O2 -std=c++17 -I"$XMRIG_DIR/src" "$here/xmrig_parity.cpp" support.o \
    libxmrig_randomx.a libargon2.a -lpthread -o "$here/xmrig_parity"

echo "built: $here/xmrig_parity"

# Build-graph isolation assertion (the nm-gate analog): this GPL-linked, XMRig-only
# harness must NOT pull in any Shekyl consensus / daemon code. Its only inputs are
# XMRig's RandomX, Argon2, and the support shims — so no shekyl_* / cryptonote /
# blockchain symbol may appear. This keeps the XMRig (GPL) surface provably out of
# the daemon's build graph, the same contract scripts/ci/check_randomx_symbol_isolation.sh
# enforces on shekyld (from the other direction).
echo "== build-graph isolation check =="
if nm "$here/xmrig_parity" 2>/dev/null | grep -qiE 'shekyl_|cryptonote::|Blockchain'; then
  echo "FAIL: harness links Shekyl consensus/daemon symbols — build-graph isolation broken"
  nm "$here/xmrig_parity" | grep -iE 'shekyl_|cryptonote::|Blockchain' | head
  exit 1
fi
echo "OK: XMRig-only harness, no Shekyl consensus symbols (GPL surface isolated from the daemon)"
