// Copyright (c) 2025-2026, The Shekyl Foundation
//
// All rights reserved.
// BSD-3-Clause

//! Generate the FCMP++ reference-block age-window constants from the JSON
//! authority at `config/consensus_constants.json`, exactly as
//! `rust/shekyl-engine-core/build.rs` and `rust/shekyl-difficulty/build.rs`
//! do. The same JSON drives the C++ header generator
//! (`cmake/generate_consensus_constants.py`), so the submit engine's
//! ref-age arithmetic (DAEMON_SUBMIT_VERDICT.md §3.1 Phase C) cannot drift
//! from the C++ consensus check it mirrors.

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn get_u64(map: &BTreeMap<String, serde_json::Value>, key: &str, source: &Path) -> u64 {
    map.get(key)
        .and_then(serde_json::Value::as_u64)
        .unwrap_or_else(|| {
            panic!(
                "missing or invalid u64 key {key:?} in {source}",
                source = source.display()
            )
        })
}

fn main() {
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("missing CARGO_MANIFEST_DIR"));
    // shekyl-daemon-rpc lives at rust/shekyl-daemon-rpc; the workspace JSON
    // authority is two levels up at config/.
    let config_path = manifest_dir
        .parent()
        .expect("workspace/rust path expected")
        .parent()
        .expect("workspace root path expected")
        .join("config")
        .join("consensus_constants.json");

    println!("cargo:rerun-if-changed={}", config_path.display());

    let raw = fs::read_to_string(&config_path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", config_path.display()));
    let map: BTreeMap<String, serde_json::Value> = serde_json::from_str(&raw)
        .unwrap_or_else(|e| panic!("invalid JSON in {}: {e}", config_path.display()));

    let min_age = get_u64(&map, "fcmp_reference_block_min_age", &config_path);
    let max_age = get_u64(&map, "fcmp_reference_block_max_age", &config_path);

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("missing OUT_DIR"));
    let out_file = out_dir.join("submit_consensus_constants.rs");

    let output = format!(
        "// @generated by build.rs from config/consensus_constants.json — do not edit.\n\
         //\n\
         // Single source of truth: `config/consensus_constants.json`. The C++\n\
         // header at `shekyl/consensus_constants_generated.h` is emitted from\n\
         // the same JSON by `cmake/generate_consensus_constants.py`.\n\
         pub const FCMP_REFERENCE_BLOCK_MIN_AGE: u64 = {min_age};\n\
         pub const FCMP_REFERENCE_BLOCK_MAX_AGE: u64 = {max_age};\n",
    );

    fs::write(&out_file, output).expect("failed writing generated consensus constants");
}
