#!/usr/bin/env bash
# Copyright (c) 2025-2026, The Shekyl Foundation
#
# Generate the per-instance configs for one fleet host. Emits nothing else:
# no installs, no service starts, no network calls. Run it, read the files it
# wrote, then decide.
#
# The fleet runs on STAGENET (Q12-R12, §11.4) — a distinct NETWORK_ID and empty
# compiled seed lists in the SHIPPED binary, so the fleet and a user's install
# are the same artifact and no isolation build is made. Ports are therefore
# 13021/13029, and the per-instance ports below deliberately avoid them so a
# hardcoded testnet or stagenet default cannot silently reach a live network.
#
# Roles:
#   anon      shekyld + its own tor process, DataDirectory and hidden service.
#             Counts toward `A`, the run's independent variable.
#   clearnet  shekyld only, public zone. The isolation detector (Q12-R3); held
#             at a fixed 15 across all arms so `A` is the only variable.
#
# Usage: gen_host_configs.sh <out-dir> <role> <count> [<start-index>]
#
# Exit:  0  configs written
#        2  bad invocation

set -euo pipefail

if [ "$#" -lt 3 ] || [ "$#" -gt 4 ]; then
  echo "usage: $0 <out-dir> <anon|clearnet> <count> [<start-index>]" >&2
  exit 2
fi

OUT="$1"; ROLE="$2"; COUNT="$3"; START="${4:-0}"
case "$ROLE" in anon|clearnet) ;; *) echo "REFUSE: role must be anon or clearnet" >&2; exit 2 ;; esac

# One block of ten per instance keeps every port derivable from the index, so a
# misfiled config is visible rather than merely wrong.
PORT_BASE="${PORT_BASE:-21000}"
# The onion advertises the stagenet default; only the FORWARDING target is the
# per-instance port. The two are different kinds of thing (§9.3).
VPORT=13021
TOR_BIN="${TOR_BIN:-/opt/shekyl-tor/tor}"
DATA_ROOT="${DATA_ROOT:-/var/lib/shekyl-fleet}"
TOR_ROOT="${TOR_ROOT:-/var/lib/shekyl-fleet-tor}"
LOG_ROOT="${LOG_ROOT:-/var/log/shekyl-fleet}"

mkdir -p "$OUT"

for offset in $(seq 0 $((COUNT - 1))); do
  i=$((START + offset))
  base=$((PORT_BASE + i * 10))
  p2p=$((base + 0)); rpc=$((base + 1)); anon_in=$((base + 2)); socks=$((base + 3))

  {
    echo "# fleet instance $i ($ROLE) — generated by gen_host_configs.sh"
    echo "stagenet=1"
    echo "data-dir=$DATA_ROOT/$i"
    echo "log-file=$LOG_ROOT/node-$i.log"
    echo "log-level=1"
    echo "p2p-bind-ip=0.0.0.0"
    echo "p2p-bind-port=$p2p"
    echo "rpc-bind-ip=127.0.0.1"
    echo "rpc-bind-port=$rpc"
    echo "no-igd=1"
    echo "hide-my-port=1"
    if [ "$ROLE" = anon ]; then
      # 12 is F-8b's floor. Below it the daemon REFUSES to start rather than
      # clamping — confirmed by walking into it: "--tx-proxy outbound count 10
      # is below the floor of 12 that the relay embargo derivation assumes".
      echo "tx-proxy=tor,127.0.0.1:$socks,12"
      echo "# anonymous-inbound is appended once this instance's onion exists."
      echo "# add-peer lines are appended in phase 4 — NOT before the"
      echo "# reachability gate passes, because a dial that fails while a"
      echo "# descriptor is still unfetchable suppresses that onion for an hour"
      echo "# (Q12-R13)."
    fi
  } > "$OUT/node-$i.conf"

  if [ "$ROLE" = anon ]; then
    {
      echo "# fleet instance $i tor — generated by gen_host_configs.sh"
      echo "SocksPort $socks"
      echo "DataDirectory $TOR_ROOT/$i"
      echo "HiddenServiceDir $TOR_ROOT/$i/hs"
      echo "HiddenServiceVersion 3"
      echo "HiddenServicePort $VPORT 127.0.0.1:$anon_in"
      echo "Log notice file $LOG_ROOT/tor-$i.log"
    } > "$OUT/tor-$i.torrc"
  fi

  echo "instance $i ($ROLE): p2p=$p2p rpc=$rpc anon-in=$anon_in socks=$socks"
done

echo
echo "Wrote $COUNT $ROLE config(s) to $OUT. Nothing was installed or started."
echo "Next: install to /etc/shekyl-fleet, start skl-tor@<i> ONLY, collect the"
echo "onions, then follow the four phases in wait_onions_reachable.sh."
