#define DEF_SHEKYL_VERSION_TAG "0db9887d3"
#define DEF_SHEKYL_VERSION "3.1.0"
#define DEF_SHEKYL_RELEASE_NAME "Shekyl NG"
#define DEF_SHEKYL_VERSION_FULL DEF_SHEKYL_VERSION "-" DEF_SHEKYL_VERSION_TAG
#define DEF_SHEKYL_VERSION_IS_RELEASE false

#include "version.h"

const char* const SHEKYL_VERSION_TAG = DEF_SHEKYL_VERSION_TAG;
const char* const SHEKYL_VERSION = DEF_SHEKYL_VERSION;
const char* const SHEKYL_RELEASE_NAME = DEF_SHEKYL_RELEASE_NAME;
const char* const SHEKYL_VERSION_FULL = DEF_SHEKYL_VERSION_FULL;
const bool SHEKYL_VERSION_IS_RELEASE = DEF_SHEKYL_VERSION_IS_RELEASE;
