// Copyright (c) 2025-2026, The Shekyl Foundation
//
// All rights reserved.
// BSD-3-Clause

//! Phase 2g Rust/C differential test harness library surface.
//!
//! Per `docs/design/RANDOMX_V2_PHASE2G_PLAN.md` §5.1.2 + §5.1.4, this
//! `[lib]` target exists **solely** so integration tests under
//! `tests/` and the §5.2.6 `gen-canonical-outputs` binary can call
//! into the harness's modules at C5+; it is not a public-API crate.
//! The crate-level `#![doc(hidden)]` attribute hides the entire
//! surface from rustdoc per §5.1.2's `#[doc(hidden)]` annotation,
//! so consumers reading `cargo doc --workspace` output do not see
//! the harness's internals as a documented surface.
//!
//! ## Visibility note
//!
//! Module items are declared `pub` (rather than the plan-doc's
//! `pub(crate)` text) because Cargo treats `src/bin/*.rs` binaries
//! as separate crates that consume the library through its `pub`
//! API. The §5.6 sole-binary invariant (no other workspace member
//! depends on `shekyl-randomx-differential`; T14 asserts via
//! `cargo metadata`) plus the `#![doc(hidden)]` crate-level
//! attribute preserve the *spirit* of `pub(crate)` — the modules
//! are not consumed by any code outside the harness. The
//! plan-doc's `pub(crate)` text in §5.1.5–§5.1.14 / §5.1.17 /
//! §5.1.18 is a minor imprecision; the substrate-correct
//! visibility is `pub` for binary access while preserving the
//! harness-internal scope via the sole-binary invariant.
//!
//! ## C5a scope (per §3.18 R6-D2 split + R6-D4)
//!
//! C5a lands `corpus_random` (populated) + `adversarial_corpus`
//! (scaffolded empty per R6-D2) + `canonical_outputs` (populated
//! at nightly sizing per R6-D4: 1024 random-corpus hashes + 32
//! cache-SHA-256 fingerprints generated by `gen-canonical-outputs`
//! against the C reference). C5b fills the adversarial corpus via
//! the grinding tool. C6 lands `cache_precondition`, `c_oracle`,
//! and `rust_subject`. C7–C9 land the mode modules + failure
//! output + invocation banner per §8.1.
//!
//! ## §5.7 drift-prevention boundary
//!
//! The re-export surface is limited to modules enumerated in
//! §5.1.5–§5.1.14 + §5.1.17 + §5.1.18. Per §5.7's reviewer
//! rejection criterion, any added module not listed in §5.1 is
//! grounds for scope-creep rejection.

#![doc(hidden)]

pub mod adversarial_corpus;
pub mod canonical_outputs;
pub mod corpus_random;
