// Copyright (c) 2025-2026, The Shekyl Foundation
//
// All rights reserved.
// BSD-3-Clause

//! Phase 2g Rust/C differential test harness library surface.
//!
//! Per `docs/design/RANDOMX_V2_PHASE2G_PLAN.md` §5.1.2 + §5.1.4, this
//! `[lib]` target exists **solely** so integration tests under
//! `tests/` and the §5.2.6 `gen-canonical-outputs` binary (a
//! separately-compiled `src/bin/*.rs` crate per Cargo's binary
//! convention) can call into the harness's `pub` modules at C5+;
//! it is not a public-API crate. Module items are declared `pub`
//! rather than `pub(crate)` because integration tests and binaries
//! consume the library as a separate crate — see the "Visibility
//! note" section below for the substrate correction against the
//! plan-doc's `pub(crate)` text. The crate-level `#![doc(hidden)]`
//! attribute hides the entire surface from rustdoc per §5.1.2's
//! `#[doc(hidden)]` annotation, so consumers reading
//! `cargo doc --workspace` output do not see the harness's
//! internals as a documented surface.
//!
//! ## Visibility note
//!
//! Module items are declared `pub` (rather than the plan-doc's
//! `pub(crate)` text) because Cargo treats `src/bin/*.rs` binaries
//! as separate crates that consume the library through its `pub`
//! API. The §5.6 sole-binary invariant (no other workspace member
//! depends on `shekyl-randomx-differential`; T14 asserts via
//! `cargo metadata`) plus the `#![doc(hidden)]` crate-level
//! attribute preserve the *spirit* of `pub(crate)` — the modules
//! are not consumed by any code outside the harness. The
//! plan-doc's `pub(crate)` text in §5.1.5–§5.1.14 / §5.1.17 /
//! §5.1.18 is a minor imprecision; the substrate-correct
//! visibility is `pub` for binary access while preserving the
//! harness-internal scope via the sole-binary invariant.
//!
//! ## Commit-by-commit scope (per §8.1)
//!
//! - **C5a:** `corpus_random` (populated) + `adversarial_corpus`
//!   (scaffolded empty per R6-D2) + `canonical_outputs` (populated
//!   at nightly sizing per R6-D4: 1024 random-corpus hashes + 32
//!   cache-SHA-256 fingerprints generated by `gen-canonical-outputs`
//!   against the C reference).
//! - **C5b:** Round 7 substrate-completeness amendment: R1-D5 +
//!   R1-D6 disposition reopening + adversarial-corpus methodology
//!   deferral to a post-2g design round per
//!   `RANDOMX_V2_PHASE2G_PLAN.md` §3.19 R7-D1 through R7-D5; no
//!   code surface lands at C5b (the adversarial corpus stays
//!   scaffolded-empty through 2g ship).
//! - **C6:** `c_oracle` (§5.1.8 safe FFI wrapper) + `rust_subject`
//!   (§5.1.9 Phase-2F-frozen-surface wrapper) +
//!   `cache_precondition` (§5.1.7 R1-D14 SHA-256 + T4 byte-diff).
//! - **C7:** `mode_correctness` (§5.1.10) + `mode_latency`
//!   (§5.1.12) implementations.
//! - **C8:** `mode_concurrent` (§5.1.13) implementation +
//!   RSS-bound assertion (T7 + T8).
//! - **C9:** `failure_output` (§5.1.14) `FailureOutput` schema +
//!   T11 round-trip + `invocation_banner` (§5.1.18) §4.6 M4
//!   stderr banner + T17 substring assertions; the
//!   `tests/perf/per_hash_latency.rs` C++-era placeholder in
//!   `shekyl-pow-randomx` is deleted per §5.3.2 + R1-D7 audit-
//!   trail discipline ("closes Phase 2c R3-minor-2"); worst-case
//!   stays deferred per §3.19 R7-D4.
//!
//! ## §5.7 drift-prevention boundary
//!
//! The re-export surface is limited to modules enumerated in
//! Phase 2g §5.1.5–§5.1.14 + §5.1.17 + §5.1.18 plus modules added
//! by Phase 2h's implementation-commit plan per
//! [`docs/design/RANDOMX_V2_PHASE2H_PLAN.md`](../../../docs/design/RANDOMX_V2_PHASE2H_PLAN.md).
//! Per the parent drift-prevention discipline, any module added
//! outside an enumerated commit is grounds for scope-creep
//! rejection.
//!
//! ## Phase 2h additions
//!
//! Phase 2h extends the harness with recipe-derived adversarial
//! corpus, first-class recipe evaluator, Family-1 canonical outputs,
//! and `--mode=adversarial-ratio`. Module additions:
//!
//! - **C1:** `adversarial_canonical_outputs` (Round 3 Pass-3
//!   measurement-derived constants + Family-1 canonical-output
//!   array scaffold per R1-D4); the array's contents populate at
//!   C5 alongside the recipe corpus that produces them.
//! - **C3:** `adversarial` (R1-D3 close recipe-based corpus
//!   methodology). Lands the `adversarial/types.rs` `CacheRecipe`
//!   + `BaseSeedhash` + `EvaluatedRecipe` data types, the
//!   `adversarial/interpreter.rs` first-class recipe evaluator
//!   (per R1-D3 close + R2-D1 T-A13 evaluator-divergence
//!   mitigation anchor), the per-category `adversarial/recipes/`
//!   sub-modules (scaffold-empty at C3; C4 populates), and the
//!   `adversarial::get_corpus()` aggregation surface. The
//!   pre-Phase-2h `adversarial_corpus.rs` module (Phase 2g R7-D4
//!   scaffolded-empty shape) stays in place at C3 and is
//!   decommissioned at C5 once the new methodology's M1
//!   canonical-output surface fully supersedes T10's role.
//! - **C6:** `mode_adversarial_ratio` (Phase 2h R1-D5 close;
//!   replaces the Phase 2g `mode_worst_case` deferred-stub
//!   dispatch at `main.rs:492-510`). Implements the per-recipe
//!   ratio + per-class systematic-regression measurement against
//!   paired
//!   [`rust_subject::RustSubjectSession::from_raw_for_testing`] /
//!   [`c_oracle::COracleSession::from_raw_for_testing`] sessions
//!   (R1-D2 close cache-level test-internals surface + C-side
//!   symmetric counterpart).

#![doc(hidden)]

pub mod adversarial;
pub mod adversarial_canonical_outputs;
pub mod adversarial_corpus;
pub mod c_oracle;
pub mod cache_precondition;
pub mod canonical_outputs;
pub mod corpus_random;
pub mod failure_output;
pub mod invocation_banner;
pub mod mode_adversarial_ratio;
pub mod mode_concurrent;
pub mod mode_correctness;
pub mod mode_latency;
pub mod rust_subject;
