// Copyright (c) 2016-2022, The Monero Project
//
// All rights reserved.
//
// Redistribution and use in source and binary forms, with or without modification, are
// permitted provided that the following conditions are met:
//
// 1. Redistributions of source code must retain the above copyright notice, this list of
//    conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright notice, this list
//    of conditions and the following disclaimer in the documentation and/or other
//    materials provided with the distribution.
//
// 3. Neither the name of the copyright holder nor the names of its contributors may be
//    used to endorse or promote products derived from this software without specific
//    prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY
// EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
// MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
// THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
// SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
// PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
// INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
// STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF
// THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#include "gtest/gtest.h"
#include "cryptonote_basic/cryptonote_basic_impl.h"
#include "wallet/wallet2.h"

static constexpr const char* TEST_URI_ADDRESS =
  "shekyl1qyattn30rnzm6adcf875l53ecr9yvcv02zdjl4vht88qce5cra6jmg60kp3380w6w829nzf7lmqlt739awnykr2grlc77em5sa459lwdnuydmcqlgupzwsa2dwfcq4jj9wh3uwz776qgequ7fzyujt3gt7898dstqagjvd454kp8j3wytw6pugvpw254f3uv7kyj52sf2rdnr4car4nr2/skpq1m5grcsrhc4l0cr6dkqcgr5rpc7dmy3nzc0ley3nnymp9ukru02kvyayvxpwpzg03mqvnjw9dg2cmsvdjgth5q66vx8pn8wtcwzyr2vh52d4dq87znxkl7v4sez4ksu0xnpmks36e0wv92ajdx7ufpem9065v9v2vcqkza9k9hxayfe8vys7nerkh7z7pd5uetzrqa8hhrzmzdscfc9nvy77rf3ckqdw3hlza4qkm0jhdpv9x6tgx8r4zy0ln90vzyke7p9f9dvfn4p3vd69dfslpmfzw02cvlxqv3d9yj6xvx6gw4jx2hqfr32n5yev3k4u8e9xcszkwfpuk0aysz5pungut5yan0gd8seaw2myu7t52d0n7jl9czgtlfyenlgcycpxr5tf78y8anpur2v2uuktjkwxprxv3x2pkxs8ducmmqznncl3gf4eacpynkg5wn3dy57psxmsrzzy0cr96k7wxqfwxknu25dmcppmwq0x7vyd454jm5kxyx5rr9jdv90tquwr7fh9709sq7gfugutmp2l4s6xsdajdw8cvtqgszgnk2sj0ujcfkaqlyj38cn6q2my2s6s5gs90yyu3xdcfq8wvxxs8s6uxgae8my2ak92vxddnjdzjsq7m649fnjtessdjjsn4yshlqjdtpfm4vw6vt3emy2pgjk3sfsf0uq4t2pctrlpr0lk8t427g43jszv7jcfhjjvp7kvjf04jfdj379uafsvr7xxztd7qqgyh4y8rujz7r772ry26wes69gpktyy84wwgdj7023g49qd43ve4rf2hm9hfp52fgmmtvlemf62htt0n2excdaeghgjxdfg8nmnksua4qe3qluxtla2t5vwegqecszttkwry9u98auag6zxq49tl3zkgz6h8x3q7wdftzx5cr66fg5un7vh8ne4s4xmkx64uceeq20hzvf/skpq21czfcp4unkq2xqlacqy4txmawchzfjktn4pr4nnxvxzpaw756tjll0qut4gv2gujxqv730j6y9vx2u3nxdwf9sgg2en4t4dz34wpnu4fpwg9htgdud0prshhp7etz8y2s0nv9hee2kdlhfgusuad9q8r54maypnvcgrdhjpn2mw3uas4usej4a0j8xme6s7gvmw4y72tn49wp8zxfk266hrjcuf7qjv4mrzse5rzg25c05etygfkt97gxkgsraxv38jzct2fd2jac7xjrw5p6svh52r4upqctwujxvearx5ju44mjft4qt5xpyft074umxxmc0pjyt6sys789g5daa3uds7a274fg2npxhzp8vcm6vwfzd2qtyu58ca9qttaqvxxm5y9twe48emh9tht72ay8kee4sxp2huardygjrtejgngs6ytrklqzavpjtfu892hfwy4jqzt8uwptcq58r79245jdgz2qj6hfl7gu20q6wtyz3vtlv6rhdyz3cydrpqftm9gvdpfrz77x5eqp8h962jj629jtt3djsm89tp8asqtnevanqx2skvnxwr77ng3q4ksm6ajx03dfje2z996cyr882tq428ujd83zrmq4qa52399clwd0tn64p9e9xngaegp09gguq7cws753v3v4grw53np9v9kvmcq4jga9uu692mxyyf7esa6wnkkzqtvucfy53pvfv2svv5vrhv5036se8u6gr68vvskmng6q6dxx4xkvqt4t47gmxwhvsfj45sfwx0cplwt496f6dj9g53muvaa7w5vr587jxn2gq8vnvj5a6gq585eyj0322ywz30g974f0pwjhprd8k0yev34uc4e37532nc96pzs8ja39x8fvegx90p2v0exz8ts4vf9tauzt83v7lggmjc30m0zkheefncgyazef9y4p7pelllmq97xfqc";

class uri : public ::testing::Test
{
protected:
  void SetUp() override
  {
    // Pinned literal, not a struct re-encode: since the fork-(ii)
    // address layout, get_account_address_as_str cannot rebuild an
    // address from account_public_address alone (no msg_sign_pk field),
    // and these tests only need SOME valid mainnet address to ride the
    // URIs. Generated by the Rust layout owner
    // (shekyl-wire tests/emit_regtest_addr.rs, fakechain seed 0x11,
    // mainnet HRP); parse_uri validates it through the same FFI decoder
    // production uses, so a layout drift still fails here loudly.
    test_address = TEST_URI_ADDRESS;
  }

  std::string test_address;
};

#define PARSE_URI(uri, expected) \
  std::string address, payment_id, recipient_name, description, error; \
  uint64_t amount; \
  std::vector<std::string> unknown_parameters; \
  tools::wallet2 w(cryptonote::MAINNET); \
  bool ret = w.parse_uri(uri, address, payment_id, amount, description, recipient_name, unknown_parameters, error); \
  ASSERT_EQ(ret, expected);

TEST_F(uri, empty_string)
{
  PARSE_URI("", false);
}

TEST_F(uri, no_scheme)
{
  PARSE_URI("shekyl", false);
}

TEST_F(uri, bad_scheme)
{
  PARSE_URI("http://foo", false);
}

TEST_F(uri, scheme_not_first)
{
  PARSE_URI(" shekyl:", false);
}

TEST_F(uri, no_body)
{
  PARSE_URI("shekyl:", false);
}

TEST_F(uri, no_address)
{
  PARSE_URI("shekyl:?", false);
}

TEST_F(uri, bad_address)
{
  PARSE_URI("shekyl:44444", false);
}

TEST_F(uri, good_address)
{
  const std::string uri_str = "shekyl:" + test_address;
  PARSE_URI(uri_str, true);
  ASSERT_EQ(address, test_address);
}

TEST_F(uri, good_integrated_address)
{
  const std::string uri_str = "shekyl:" + test_address;
  PARSE_URI(uri_str, true);
}

TEST_F(uri, parameter_without_inter)
{
  PARSE_URI("shekyl:" + test_address + "&amount=1", false);
}

TEST_F(uri, parameter_without_equals)
{
  PARSE_URI("shekyl:" + test_address + "?amount", false);
}

TEST_F(uri, parameter_without_value)
{
  PARSE_URI("shekyl:" + test_address + "?tx_amount=", false);
}

TEST_F(uri, negative_amount)
{
  PARSE_URI("shekyl:" + test_address + "?tx_amount=-1", false);
}

TEST_F(uri, bad_amount)
{
  PARSE_URI("shekyl:" + test_address + "?tx_amount=alphanumeric", false);
}

TEST_F(uri, duplicate_parameter)
{
  PARSE_URI("shekyl:" + test_address + "?tx_amount=1&tx_amount=1", false);
}

TEST_F(uri, unknown_parameter)
{
  PARSE_URI("shekyl:" + test_address + "?unknown=1", true);
  ASSERT_EQ(unknown_parameters.size(), 1u);
  ASSERT_EQ(unknown_parameters[0], "unknown=1");
}

TEST_F(uri, unknown_parameters)
{
  PARSE_URI("shekyl:" + test_address + "?tx_amount=1&unknown=1&tx_description=desc&foo=bar", true);
  ASSERT_EQ(unknown_parameters.size(), 2u);
  ASSERT_EQ(unknown_parameters[0], "unknown=1");
  ASSERT_EQ(unknown_parameters[1], "foo=bar");
}

TEST_F(uri, empty_payment_id)
{
  PARSE_URI("shekyl:" + test_address + "?tx_payment_id=", false);
}

TEST_F(uri, bad_payment_id)
{
  PARSE_URI("shekyl:" + test_address + "?tx_payment_id=1234567890", false);
}

TEST_F(uri, short_payment_id)
{
  PARSE_URI("shekyl:" + test_address + "?tx_payment_id=1234567890123456", false);
}

TEST_F(uri, long_payment_id)
{
  PARSE_URI("shekyl:" + test_address + "?tx_payment_id=1234567890123456789012345678901234567890123456789012345678901234", true);
  ASSERT_EQ(address, test_address);
  ASSERT_EQ(payment_id, "1234567890123456789012345678901234567890123456789012345678901234");
}

TEST_F(uri, payment_id_with_integrated_address)
{
  PARSE_URI("shekyl:" + test_address + "?tx_payment_id=1234567890123456", false);
}

TEST_F(uri, empty_description)
{
  PARSE_URI("shekyl:" + test_address + "?tx_description=", true);
  ASSERT_EQ(description, "");
}

TEST_F(uri, empty_recipient_name)
{
  PARSE_URI("shekyl:" + test_address + "?recipient_name=", true);
  ASSERT_EQ(recipient_name, "");
}

TEST_F(uri, non_empty_description)
{
  PARSE_URI("shekyl:" + test_address + "?tx_description=foo", true);
  ASSERT_EQ(description, "foo");
}

TEST_F(uri, non_empty_recipient_name)
{
  PARSE_URI("shekyl:" + test_address + "?recipient_name=foo", true);
  ASSERT_EQ(recipient_name, "foo");
}

TEST_F(uri, url_encoding)
{
  PARSE_URI("shekyl:" + test_address + "?tx_description=foo%20bar", true);
  ASSERT_EQ(description, "foo bar");
}

TEST_F(uri, non_alphanumeric_url_encoding)
{
  PARSE_URI("shekyl:" + test_address + "?tx_description=foo%2x", true);
  ASSERT_EQ(description, "foo%2x");
}

TEST_F(uri, truncated_url_encoding)
{
  PARSE_URI("shekyl:" + test_address + "?tx_description=foo%2", true);
  ASSERT_EQ(description, "foo%2");
}

TEST_F(uri, percent_without_url_encoding)
{
  PARSE_URI("shekyl:" + test_address + "?tx_description=foo%", true);
  ASSERT_EQ(description, "foo%");
}

TEST_F(uri, url_encoded_once)
{
  PARSE_URI("shekyl:" + test_address + "?tx_description=foo%2020", true);
  ASSERT_EQ(description, "foo 20");
}
