//! Generate the canonical atomic-unit denomination constants from
//! `config/economics_params.json` — the single source of truth shared with
//! `shekyl-economics`, `shekyl-difficulty`, and `shekyl-staking`.
//!
//! Emits `ATOMIC_UNITS_PER_SKL: u64` (the `coin` field) and
//! `DISPLAY_DECIMAL_POINT: u8` (the `display_decimal_point` field) so that
//! `AtomicUnits` owns the `10^9` relationship without a hardcoded literal.
//! A build-time assertion guards the two JSON fields against drift
//! (`coin == 10^display_decimal_point`), mirrored by a `const _` assertion in
//! `lib.rs` for defense in depth.

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::PathBuf;

fn get_u64(map: &BTreeMap<String, serde_json::Value>, key: &str) -> u64 {
    map.get(key)
        .and_then(serde_json::Value::as_u64)
        .unwrap_or_else(|| panic!("missing or invalid u64 key in economics config: {key}"))
}

fn main() {
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("missing CARGO_MANIFEST_DIR"));
    let config_path = manifest_dir
        .parent()
        .expect("workspace/rust path expected")
        .parent()
        .expect("workspace root path expected")
        .join("config")
        .join("economics_params.json");

    println!("cargo:rerun-if-changed={}", config_path.display());

    let raw = fs::read_to_string(&config_path).expect("failed to read economics_params.json");
    let map: BTreeMap<String, serde_json::Value> =
        serde_json::from_str(&raw).expect("invalid JSON in economics_params.json");

    let coin = get_u64(&map, "coin");
    let decimals = get_u64(&map, "display_decimal_point");

    // `DISPLAY_DECIMAL_POINT` is emitted as a `u8`; the value (9) fits with
    // room to spare. A wider value would be a config error, not a runtime
    // condition, so failing the build is correct.
    let decimals_u8 = u8::try_from(decimals)
        .unwrap_or_else(|_| panic!("display_decimal_point {decimals} does not fit u8"));
    let decimals_pow =
        u32::try_from(decimals).unwrap_or_else(|_| panic!("display_decimal_point too large"));

    // Drift guard: the headline supply (2^32 whole SKL) is representable in
    // u64 only because `coin == 10^display_decimal_point` at decimals <= 9.
    // If the two JSON fields ever disagree, the denomination is incoherent.
    let expected = 10u64
        .checked_pow(decimals_pow)
        .unwrap_or_else(|| panic!("10^{decimals} overflows u64"));
    assert!(
        coin == expected,
        "economics_params.json drift: coin ({coin}) != 10^display_decimal_point ({expected})"
    );

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("missing OUT_DIR"));
    let out_file = out_dir.join("units_generated.rs");

    let output = format!(
        "// @generated by build.rs from config/economics_params.json — do not edit.\n\
         /// Atomic units per whole SKL (`coin` in economics_params.json).\n\
         ///\n\
         /// `10^9`: the largest decimal precision under which a `2^32` whole-SKL\n\
         /// supply stays representable in `u64` (see ATOMIC_UNITS_NEWTYPE.md §6).\n\
         pub const ATOMIC_UNITS_PER_SKL: u64 = {coin};\n\
         /// Display decimal places for SKL formatting (`display_decimal_point`).\n\
         pub const DISPLAY_DECIMAL_POINT: u8 = {decimals_u8};\n"
    );

    fs::write(&out_file, output).expect("failed writing generated units constants");
}
