//! Generate the FCMP reference-block age bounds and CT type from the JSON
//! authority at `config/consensus_constants.json` — the same source
//! `cmake/generate_consensus_constants.py` (C++ header) and
//! `rust/shekyl-engine-core/build.rs` read, so the languages cannot drift.
//!
//! `src/intent.rs` `include!`s the emitted file; const-evaluated `assert!`
//! blocks at the consumption sites pin meaning across changes. Only the three
//! constants `intent.rs` consumes are emitted here (engine-core's build.rs also
//! emits `ARCHIVAL_BOND_FLOOR_ATOMIC`, which this crate has no use for).

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn get_u64(map: &BTreeMap<String, serde_json::Value>, key: &str, source: &Path) -> u64 {
    map.get(key)
        .and_then(serde_json::Value::as_u64)
        .unwrap_or_else(|| {
            panic!(
                "missing or invalid u64 key {key:?} in {source}",
                source = source.display()
            )
        })
}

fn main() {
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("missing CARGO_MANIFEST_DIR"));
    // shekyl-multisig lives at rust/shekyl-multisig; the workspace JSON
    // authority is two levels up at config/.
    let config_path = manifest_dir
        .parent()
        .expect("workspace/rust path expected")
        .parent()
        .expect("workspace root path expected")
        .join("config")
        .join("consensus_constants.json");

    println!("cargo:rerun-if-changed={}", config_path.display());

    let raw = fs::read_to_string(&config_path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", config_path.display()));
    let map: BTreeMap<String, serde_json::Value> = serde_json::from_str(&raw)
        .unwrap_or_else(|e| panic!("invalid JSON in {}: {e}", config_path.display()));

    let min_age = get_u64(&map, "fcmp_reference_block_min_age", &config_path);
    let max_age = get_u64(&map, "fcmp_reference_block_max_age", &config_path);
    // Convert to the destination type at the boundary so a JSON value > 255
    // fails the build here with a clear message rather than emitting an
    // out-of-range literal the consumer would reject.
    let ct_type_raw = get_u64(&map, "ct_type_fcmp_plus_plus_pqc", &config_path);
    let ct_type: u8 = u8::try_from(ct_type_raw).unwrap_or_else(|_| {
        panic!(
            "ct_type_fcmp_plus_plus_pqc must fit in u8 (got {ct_type_raw}) in {}",
            config_path.display()
        )
    });

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("missing OUT_DIR"));
    let out_file = out_dir.join("consensus_constants_generated.rs");

    let output = format!(
        "// @generated by build.rs from config/consensus_constants.json — do not edit.\n\
         //\n\
         // Single source of truth: `config/consensus_constants.json`. The C++\n\
         // header at `shekyl/consensus_constants_generated.h` is emitted from\n\
         // the same JSON by `cmake/generate_consensus_constants.py`.\n\
         pub const FCMP_REFERENCE_BLOCK_MIN_AGE: u64 = {min_age};\n\
         pub const FCMP_REFERENCE_BLOCK_MAX_AGE: u64 = {max_age};\n\
         pub const CT_TYPE_FCMP_PLUS_PLUS_PQC: u8 = {ct_type};\n",
    );

    fs::write(&out_file, output).expect("failed writing generated consensus constants");
}
