//! Generate the LWMA-1 window-shape constants from the JSON authority
//! at `config/consensus_constants.json`. The same JSON drives the C++
//! header generator at `cmake/generate_consensus_constants.py` so the
//! two languages cannot drift.
//!
//! Bug class motivation: Bug 3 of the 2026-05-05 FFI constant-drift
//! audit (`docs/audit_trail/2026-05-ffi-constant-drift-audit.md`). The
//! pattern mirrors `rust/shekyl-engine-core/build.rs`; the per-crate
//! `build.rs` (rather than centralizing in `shekyl-engine-core/build.rs`)
//! is the Round 3 disposition recorded in
//! `docs/design/DAA_LWMA1_PLAN.md` Phase 1 — extending the engine-core
//! build script would break this crate's leaf property (zero internal
//! workspace deps per `docs/design/DAA_LWMA1.md` §2.1).
//!
//! Per Round 3 (DAA_LWMA1.md §4): only the window-shape constants are
//! emitted here — `N`, `T_SECONDS`, `FTL_SECONDS`, `MTP_WINDOW`,
//! `GENESIS_DIFFICULTY`. The bias factor `99/200`, solvetime clamp
//! `6`, and minimum-L floor `1/20` are deliberately NOT named: they
//! appear as bare integer literals inside `src/lwma1.rs` because
//! changing them is a deviation from canonical zawy12 LWMA-1, not a
//! tunable parameter.

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn get_u64(map: &BTreeMap<String, serde_json::Value>, key: &str, source: &Path) -> u64 {
    map.get(key)
        .and_then(serde_json::Value::as_u64)
        .unwrap_or_else(|| {
            panic!(
                "missing or invalid u64 key {key:?} in {source}",
                source = source.display()
            )
        })
}

fn main() {
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("missing CARGO_MANIFEST_DIR"));
    // shekyl-difficulty lives at rust/shekyl-difficulty; the workspace
    // JSON authority is two levels up at config/.
    let config_path = manifest_dir
        .parent()
        .expect("workspace/rust path expected")
        .parent()
        .expect("workspace root path expected")
        .join("config")
        .join("consensus_constants.json");

    println!("cargo:rerun-if-changed={}", config_path.display());

    let raw = fs::read_to_string(&config_path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", config_path.display()));
    let map: BTreeMap<String, serde_json::Value> = serde_json::from_str(&raw)
        .unwrap_or_else(|e| panic!("invalid JSON in {}: {e}", config_path.display()));

    let window_n = get_u64(&map, "daa_window_n", &config_path);
    let target_seconds = get_u64(&map, "daa_target_seconds", &config_path);
    let ftl_seconds = get_u64(&map, "daa_ftl_seconds", &config_path);
    let mtp_window = get_u64(&map, "daa_mtp_window", &config_path);
    let genesis_difficulty = get_u64(&map, "daa_genesis_difficulty", &config_path);

    // Slice-/array-indexing forms for N and MTP_WINDOW. Emitted by
    // the build script (rather than via `usize::try_from(N)` in a
    // const block) because `TryFrom::try_from` is not yet const-trait-
    // stable as of rustc 1.95.0 (issue #143874). The values are
    // already valid `u32` since they fit comfortably in
    // `consensus_constants.json`'s integer-range validation; the
    // `expect` here defends only against a future JSON edit that
    // pushes one of these above `u32::MAX`, which would itself be a
    // build-time signal that the consensus parameter has drifted
    // outside the algorithm's assumptions (zawy12 LWMA-1 with
    // `N > 2^32` is not a meaningful regime).
    let window_n_usize: u32 = u32::try_from(window_n).expect(
        "daa_window_n must fit in u32 for usize emission \
         on all supported targets",
    );
    let mtp_window_usize: u32 = u32::try_from(mtp_window).expect(
        "daa_mtp_window must fit in u32 for usize emission \
         on all supported targets",
    );

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("missing OUT_DIR"));
    let out_file = out_dir.join("consensus_constants_generated.rs");

    // The emitted constants are crate-private (no `pub`): the only
    // consumer is `src/consts.rs`, which re-exports them under the
    // doc-rich public names `N`, `T_SECONDS`, `FTL_SECONDS`,
    // `MTP_WINDOW`, `GENESIS_DIFFICULTY`. Keeping these private
    // sidesteps `#![deny(missing_docs)]` on the generated file (which
    // can't carry doc comments easily) and prevents downstream
    // consumers from accidentally depending on the JSON-key-derived
    // names.
    let output = format!(
        "// @generated by build.rs from config/consensus_constants.json — do not edit.\n\
         //\n\
         // Single source of truth: `config/consensus_constants.json`. The C++\n\
         // header at `shekyl/consensus_constants_generated.h` is emitted from\n\
         // the same JSON by `cmake/generate_consensus_constants.py`.\n\
         //\n\
         // `GENESIS_DIFFICULTY` is typed `u128` rather than `u64` per\n\
         // DAA_LWMA1.md §2.6 so the value lines up with `next_difficulty`'s\n\
         // codomain without a widening conversion at consumer call sites.\n\
         const DAA_WINDOW_N: u64 = {window_n};\n\
         const DAA_WINDOW_N_USIZE: usize = {window_n_usize};\n\
         const DAA_TARGET_SECONDS: u64 = {target_seconds};\n\
         const DAA_FTL_SECONDS: u64 = {ftl_seconds};\n\
         const DAA_MTP_WINDOW: u64 = {mtp_window};\n\
         const DAA_MTP_WINDOW_USIZE: usize = {mtp_window_usize};\n\
         const DAA_GENESIS_DIFFICULTY: u128 = {genesis_difficulty};\n",
    );

    fs::write(&out_file, output).expect("failed writing generated DAA constants");
}
