// Copyright (c) 2026, The Shekyl Foundation
//
// All rights reserved.
// BSD-3-Clause

//! Generate the shard-partition constant from the JSON authority at
//! `config/consensus_constants.json`, the same file the C++ header
//! generator (`cmake/generate_consensus_constants.py`) and the other
//! per-crate build scripts read, so the two languages cannot drift.
//!
//! Two keys are emitted here. `archival_shard_length_bytes` is the `W` of the
//! archival shard partition (`shekyl_types::SHARD_LENGTH`; `SHT-Q2`, RULED
//! 2026-09-29): shards are cut by archival length. It lives in the JSON rather than as a
//! literal because every other numeric on the Round-2 re-pin gate
//! (`settlement_epoch_blocks`, `archival_reorg_depth_blocks`,
//! `challenge_resolution_blocks`) is sourced there, and a consensus
//! numeric with two sourcing idioms is a drift waiting for a re-pin
//! (S-PRUNE review, PR #861 item 6). The per-crate `build.rs` — rather
//! than a dependency on a crate that already reads the JSON — keeps this
//! crate the `#![no_std]` leaf the rest of the vocabulary stands on
//! (`shekyl-difficulty/build.rs` is the same shape for the same reason).

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn get_u64(map: &BTreeMap<String, serde_json::Value>, key: &str, source: &Path) -> u64 {
    map.get(key)
        .and_then(serde_json::Value::as_u64)
        .unwrap_or_else(|| {
            panic!(
                "missing or invalid u64 key {key:?} in {source}",
                source = source.display()
            )
        })
}

fn main() {
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("missing CARGO_MANIFEST_DIR"));
    // shekyl-types lives at rust/shekyl-types; the workspace JSON authority
    // is two levels up at config/.
    let config_path = manifest_dir
        .parent()
        .expect("workspace/rust path expected")
        .parent()
        .expect("workspace root path expected")
        .join("config")
        .join("consensus_constants.json");

    println!("cargo:rerun-if-changed={}", config_path.display());
    println!("cargo:rerun-if-changed=build.rs");

    let raw = fs::read_to_string(&config_path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", config_path.display()));
    let map: BTreeMap<String, serde_json::Value> = serde_json::from_str(&raw)
        .unwrap_or_else(|e| panic!("invalid JSON in {}: {e}", config_path.display()));

    let shard_length_bytes = get_u64(&map, "archival_shard_length_bytes", &config_path);
    let max_holdings_shards = get_u64(&map, "archival_max_holdings_shards", &config_path);

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("missing OUT_DIR"));
    let out_file = out_dir.join("consensus_constants_generated.rs");
    // Crate-private: `src/archival/mod.rs` re-exports it as the typed
    // `SHARD_LENGTH` and carries the `> 0` sentinel.
    // `ARCHIVAL_MAX_HOLDINGS_SHARDS` is emitted as `usize`, not `u64`, because it
    // bounds a `Vec` length: emitting the width its consumer needs means there is
    // no cast to lint or to assert, and a value exceeding `usize` on a 32-bit
    // target fails to compile AT THE LITERAL rather than tripping a runtime check.
    let output = format!(
        "// @generated by build.rs from config/consensus_constants.json — do not edit.\n\
         //\n\
         // Single source of truth: `config/consensus_constants.json`.\n\
         const ARCHIVAL_SHARD_LENGTH_BYTES: u64 = {shard_length_bytes};\n\
         const ARCHIVAL_MAX_HOLDINGS_SHARDS: usize = {max_holdings_shards};\n"
    );
    fs::write(&out_file, output)
        .unwrap_or_else(|e| panic!("failed to write {}: {e}", out_file.display()));
}
