#!/usr/bin/env bash
#
# Content-integrity gate for the vendored crypto subtree (rust/shekyl-oxide/crypto/).
#
# The KEEP-VENDORED crypto crates (helioselene, divisors, generalized-bulletproofs,
# fcmps + ec-gadgets + circuit-abstraction) are a pristine mirror of the
# Shekyl-Foundation/monero-oxide@fcmp++ fork (docs/design/SHEKYL_OXIDE_UNVENDOR.md).
# They are genesis-frozen by reference (slice-1 Q6) and headed for the divisor
# EC-membership external review, so an in-place edit — the kind of drift that landed
# in `divisors` by bypassing the fork workflow — must be caught, not silently absorbed.
#
# This gate verifies the subtree byte-for-byte against a checked-in manifest
# (rust/shekyl-oxide/CRYPTO_CONTENT_MANIFEST.sha256). Any added, removed, or modified
# tracked file fails. To CHANGE vendored crypto you go through the fork
# (docs/SHEKYL_OXIDE_VENDORING.md): cherry-pick into monero-oxide@fcmp++, re-sync the
# subtree, then regenerate the manifest with `--update`. A bare local edit fails here
# by design — that is the whole point.
#
# It also has to be regenerated in a deliberate toolchain-bump PR if the bump's rustfmt
# reflows the subtree (see rust/rust-toolchain.toml's bump policy). Outside those two
# sanctioned events, a manifest change is a red flag in review.
#
# Today this is drift-from-snapshot (local == the recorded snapshot). It upgrades to
# byte-exact-vs-pin once A0 re-syncs the subtree to a clean fork baseline
# (SHEKYL_OXIDE_UNVENDOR.md §6 Track A); at that point the snapshot == the pin.
#
# Usage:
#   check_vendored_crypto_manifest.sh [--check]   # verify (default); CI gate
#   check_vendored_crypto_manifest.sh --update     # regenerate after a fork re-sync
#
set -euo pipefail

repo_root=$(git rev-parse --show-toplevel)
cd "$repo_root"

crypto_dir="rust/shekyl-oxide/crypto"
manifest="rust/shekyl-oxide/CRYPTO_CONTENT_MANIFEST.sha256"
mode="${1:---check}"

# Deterministic content snapshot: tracked files only (no build artifacts / untracked),
# byte-stable C-locale sort, sha256 per file.
compute() {
  git ls-files "$crypto_dir" | LC_ALL=C sort | xargs sha256sum
}

case "$mode" in
  --update)
    {
      echo "# Content manifest for the vendored crypto subtree ($crypto_dir/)."
      echo "# Generated by scripts/ci/check_vendored_crypto_manifest.sh --update."
      echo "# Regenerate ONLY after a monero-oxide@fcmp++ fork re-sync"
      echo "# (docs/SHEKYL_OXIDE_VENDORING.md) or a sanctioned toolchain-bump reflow —"
      echo "# never to bless a bare local edit."
      compute
    } >"$manifest"
    echo "Wrote $manifest ($(compute | wc -l) files)."
    ;;
  --check)
    if [ ! -f "$manifest" ]; then
      echo "FATAL: $manifest is missing." >&2
      exit 1
    fi
    expected=$(grep -vE '^#' "$manifest" | LC_ALL=C sort)
    actual=$(compute | LC_ALL=C sort)
    if [ "$expected" != "$actual" ]; then
      echo "FATAL: the vendored crypto subtree does not match $manifest." >&2
      echo "--- expected (manifest) vs actual (working tree) ---" >&2
      diff <(printf '%s\n' "$expected") <(printf '%s\n' "$actual") >&2 || true
      echo >&2
      echo "Vendored crypto is pristine + genesis-frozen. To change it, go through the" >&2
      echo "monero-oxide@fcmp++ fork and re-sync (docs/SHEKYL_OXIDE_VENDORING.md), then run:" >&2
      echo "  scripts/ci/check_vendored_crypto_manifest.sh --update" >&2
      exit 1
    fi
    echo "OK: vendored crypto subtree matches the manifest ($(printf '%s\n' "$actual" | wc -l) files)."
    ;;
  *)
    echo "usage: $0 [--check|--update]" >&2
    exit 2
    ;;
esac
