// Copyright (c) 2026, The Shekyl Foundation
//
// All rights reserved.
// BSD-3-Clause

//! Generate CEN-I11's reference-window ages from
//! `config/consensus_constants.json`. The same JSON drives the C++ header
//! (`cmake/generate_consensus_constants.py`) and `shekyl-curve-tree`'s
//! build script, so a hand-copied `5` / `100` cannot drift the way
//! `FCMP_REFERENCE_BLOCK_MIN_AGE = 10` did
//! (`docs/audit_trail/2026-05-ffi-constant-drift-audit.md`, Bug 3).
//!
//! A per-crate script, not a dependency on `shekyl-curve-tree`: that crate
//! is the client's tree, and two integers are not a reason to take it
//! (`17-dependency-discipline`). The consts stay beside the rule (slice 6
//! Q5); this script is where their values come from. A `const` assert next
//! to them is the sentinel a JSON edit must update on purpose.

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn get_u64(map: &BTreeMap<String, serde_json::Value>, key: &str, source: &Path) -> u64 {
    map.get(key)
        .and_then(serde_json::Value::as_u64)
        .unwrap_or_else(|| panic!("missing or invalid u64 key {key:?} in {}", source.display()))
}

fn main() {
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("missing CARGO_MANIFEST_DIR"));
    // rust/shekyl-chain-rules → repo root → config/.
    let config_path = manifest_dir
        .parent()
        .expect("workspace/rust path expected")
        .parent()
        .expect("workspace root path expected")
        .join("config")
        .join("consensus_constants.json");

    println!("cargo:rerun-if-changed={}", config_path.display());

    let raw = fs::read_to_string(&config_path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", config_path.display()));
    let map: BTreeMap<String, serde_json::Value> = serde_json::from_str(&raw)
        .unwrap_or_else(|e| panic!("invalid JSON in {}: {e}", config_path.display()));

    let min_age = get_u64(&map, "fcmp_reference_block_min_age", &config_path);
    let max_age = get_u64(&map, "fcmp_reference_block_max_age", &config_path);

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("missing OUT_DIR"));
    let output = format!(
        "// @generated by build.rs from config/consensus_constants.json — do not edit.\n\
         const FCMP_REFERENCE_BLOCK_MIN_AGE: u64 = {min_age};\n\
         const FCMP_REFERENCE_BLOCK_MAX_AGE: u64 = {max_age};\n"
    );
    fs::write(out_dir.join("reference_window_generated.rs"), output)
        .expect("failed writing generated reference window");
}
