//! Generate staking tier numeric parameters from `config/economics_params.json`
//! (same source as `shekyl-economics`).

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::PathBuf;

fn get_u64(map: &BTreeMap<String, serde_json::Value>, key: &str) -> u64 {
    map.get(key)
        .and_then(serde_json::Value::as_u64)
        .unwrap_or_else(|| panic!("missing or invalid u64 key in economics config: {key}"))
}

fn main() {
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("missing CARGO_MANIFEST_DIR"));
    let config_path = manifest_dir
        .parent()
        .expect("workspace/rust path expected")
        .parent()
        .expect("workspace root path expected")
        .join("config")
        .join("economics_params.json");

    println!("cargo:rerun-if-changed={}", config_path.display());

    let raw = fs::read_to_string(&config_path).expect("failed to read economics_params.json");
    let map: BTreeMap<String, serde_json::Value> =
        serde_json::from_str(&raw).expect("invalid JSON in economics_params.json");

    let num_tiers = get_u64(&map, "shekyl_stake_num_tiers");
    assert!(
        num_tiers == 3,
        "shekyl_stake_num_tiers must be 3 for current TIERS table (got {num_tiers})"
    );

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("missing OUT_DIR"));
    let out_file = out_dir.join("tier_params_generated.rs");

    let output = format!(
        "// @generated by build.rs from economics_params.json — do not edit.\n\
         pub const GENERATED_STAKE_TIER_SHORT_BLOCKS: u64 = {short_b};\n\
         pub const GENERATED_STAKE_TIER_MEDIUM_BLOCKS: u64 = {med_b};\n\
         pub const GENERATED_STAKE_TIER_LONG_BLOCKS: u64 = {long_b};\n\
         pub const GENERATED_STAKE_YIELD_MULT_SHORT: u64 = {short_y};\n\
         pub const GENERATED_STAKE_YIELD_MULT_MEDIUM: u64 = {med_y};\n\
         pub const GENERATED_STAKE_YIELD_MULT_LONG: u64 = {long_y};\n\
         pub const GENERATED_STAKE_MAX_CLAIM_RANGE: u64 = {claim_range};\n",
        short_b = get_u64(&map, "shekyl_stake_tier_short_blocks"),
        med_b = get_u64(&map, "shekyl_stake_tier_medium_blocks"),
        long_b = get_u64(&map, "shekyl_stake_tier_long_blocks"),
        short_y = get_u64(&map, "shekyl_stake_yield_mult_short"),
        med_y = get_u64(&map, "shekyl_stake_yield_mult_medium"),
        long_y = get_u64(&map, "shekyl_stake_yield_mult_long"),
        claim_range = get_u64(&map, "shekyl_stake_max_claim_range"),
    );

    fs::write(&out_file, output).expect("failed writing generated tier params");
}
