//! One-shot generator for the ruling-B designated-reference goldens.
//!
//! Ruling B (`docs/V3_SHARD_VISUALIZATION.md`, *Rendering determinism and
//! empirical closure*): goldens are committed **once**, from a designated
//! reference run — named implementation, named architecture, named commit —
//! and are never regenerated by the tests that consume them. This binary is
//! that reference run, not test infrastructure: `tests/ruling_b.rs` only
//! *reads* what this writes. Re-running it and committing the result is the
//! recorded-amendment path (cite the measurement that motivated it in the
//! commit message), never a way to make a red parity test pass.
//!
//! Writes, under `tests/goldens/`:
//! - `<fixture id>_128.png` — the canonical render of each corpus fixture at
//!   128×128 (the mobile thumbnail target size);
//! - `recipes.json` — every fixture's full `CandidateRecipe`, plus a
//!   `_reference_run` record naming the implementation and platform. The
//!   producing commit is named in the commit that lands the artifacts,
//!   since it cannot exist at generation time.

use std::fs;
use std::path::PathBuf;

use shekyl_shard_visual::{
    fixtures, parameters_from_aggregate, recipe_from_params, render_candidate_png_from_params,
};

const GOLDEN_SIZE: u32 = 128;

fn main() {
    let out_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/goldens");
    fs::create_dir_all(&out_dir).expect("create tests/goldens");

    let mut recipes = serde_json::Map::new();
    recipes.insert(
        "_reference_run".into(),
        serde_json::json!({
            "implementation": "shekyl-shard-visual (Rust reference)",
            "target_arch": std::env::consts::ARCH,
            "target_os": std::env::consts::OS,
            "golden_size": GOLDEN_SIZE,
            "note": "producing commit is named in the commit that lands these artifacts",
        }),
    );

    let corpus = fixtures::all();
    // An empty corpus would emit an artifact with no fixtures, against which
    // the consuming KAT compares empty to empty and passes (rule 47).
    assert!(
        !corpus.is_empty(),
        "fixture corpus is empty; nothing to generate"
    );

    for fixture in corpus {
        let params = parameters_from_aggregate(&fixture.aggregate);
        let recipe = recipe_from_params(&params);
        let png = render_candidate_png_from_params(&params, GOLDEN_SIZE).expect("render fixture");

        let png_path = out_dir.join(format!("{}_{}.png", fixture.id, GOLDEN_SIZE));
        fs::write(&png_path, &png).expect("write golden png");
        println!("wrote {} ({} bytes)", png_path.display(), png.len());

        recipes.insert(
            fixture.id.clone(),
            serde_json::to_value(&recipe).expect("serialize recipe"),
        );
    }

    let recipes_path = out_dir.join("recipes.json");
    let mut body =
        serde_json::to_string_pretty(&serde_json::Value::Object(recipes)).expect("serialize");
    body.push('\n');
    fs::write(&recipes_path, body).expect("write recipes.json");
    println!("wrote {}", recipes_path.display());
}
