//! One-shot generator for the ruling-B designated-reference goldens.
//!
//! Ruling B (`docs/V3_SHARD_VISUALIZATION.md`, *Rendering determinism and
//! empirical closure*): goldens are committed **once**, from a designated
//! reference run — named implementation, named architecture, named commit —
//! and are never regenerated by the tests that consume them. This binary is
//! that reference run, not test infrastructure: `tests/ruling_b.rs` only
//! *reads* what this writes. Re-running it and committing the result is the
//! recorded-amendment path (cite the measurement that motivated it in the
//! commit message), never a way to make a red parity test pass.
//!
//! Writes, under `tests/goldens/`:
//! - `<fixture id>_128.png` — the canonical render of each corpus fixture at
//!   128×128 (the mobile thumbnail target size);
//! - `recipes.json` — every fixture's full `CandidateRecipe`, plus a
//!   `_reference_run` record naming the implementation and platform. The
//!   producing commit is named in the commit that lands the artifacts,
//!   since it cannot exist at generation time.

use std::fs;
use std::path::PathBuf;

use shekyl_shard_visual::{
    fixtures, parameters_from_aggregate, recipe_from_params, render_candidate_png_from_params,
    RENDER_REVISION,
};

const GOLDEN_SIZE: u32 = 128;

/// Best-effort capture of a tool's output for the provenance record. A field
/// that could silently become `"unknown"` would weaken the record, so the
/// consuming KAT rejects that value rather than accepting it — better a loud
/// failure at generation time than an artifact that cannot identify its run.
fn capture(program: &str, args: &[&str]) -> String {
    std::process::Command::new(program)
        .args(args)
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .filter(|s| !s.is_empty())
        .unwrap_or_else(|| "unknown".to_string())
}

fn main() {
    // Captured ONCE, and an indeterminate result stops generation rather than
    // defaulting. `capture` returns "unknown" when the command fails, and
    // "unknown" is non-empty -- so testing it inline for non-emptiness would
    // record a tree whose state could not be read as CLEAN, which is the one
    // value the consuming KAT accepts. A provenance field must never fail
    // toward the answer that passes.
    let status = capture("git", &["status", "--porcelain"]);
    assert!(
        status != "unknown",
        "cannot determine whether the tree is clean (`git status` failed); \
         refusing to write a provenance record that would claim either state"
    );
    let dirty = !status.is_empty();

    let out_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/goldens");
    fs::create_dir_all(&out_dir).expect("create tests/goldens");

    let mut recipes = serde_json::Map::new();
    recipes.insert(
        "_reference_run".into(),
        serde_json::json!({
            "implementation": "shekyl-shard-visual (Rust reference)",
            // The revision pin. Goldens are only meaningful under the pixel
            // derivation that produced them, so the artifact records it and
            // the KAT asserts equality with the crate's exported constant: a
            // regenerated golden under an unchanged RENDER_REVISION is then a
            // caught error rather than a documented convention.
            "render_revision": RENDER_REVISION,
            "profile": if cfg!(debug_assertions) { "debug" } else { "release" },
            "rustc_version": capture("rustc", &["--version"]),
            "target_arch": std::env::consts::ARCH,
            "target_os": std::env::consts::OS,
            "target_pointer_width": usize::BITS,
            // Tree the generator read, not the commit that lands the result —
            // that one cannot exist yet. `dirty` says whether the tree carried
            // uncommitted changes, without which the sha does not identify
            // what was actually rendered.
            "source_tree_commit": capture("git", &["rev-parse", "HEAD"]),
            "source_tree_dirty": dirty,
            "golden_size": GOLDEN_SIZE,
        }),
    );

    let corpus = fixtures::all();
    // An empty corpus would emit an artifact with no fixtures, against which
    // the consuming KAT compares empty to empty and passes (rule 47).
    assert!(
        !corpus.is_empty(),
        "fixture corpus is empty; nothing to generate"
    );

    for fixture in corpus {
        let params = parameters_from_aggregate(&fixture.aggregate);
        let recipe = recipe_from_params(&params);
        let png = render_candidate_png_from_params(&params, GOLDEN_SIZE).expect("render fixture");

        let png_path = out_dir.join(format!("{}_{}.png", fixture.id, GOLDEN_SIZE));
        fs::write(&png_path, &png).expect("write golden png");
        println!("wrote {} ({} bytes)", png_path.display(), png.len());

        recipes.insert(
            fixture.id.clone(),
            serde_json::to_value(&recipe).expect("serialize recipe"),
        );
    }

    let recipes_path = out_dir.join("recipes.json");
    let mut body =
        serde_json::to_string_pretty(&serde_json::Value::Object(recipes)).expect("serialize");
    body.push('\n');
    fs::write(&recipes_path, body).expect("write recipes.json");
    println!("wrote {}", recipes_path.display());
}
