// Copyright (c) 2026, The Shekyl Foundation
//
// All rights reserved.
// BSD-3-Clause

//! Emit `ARCHIVAL_BOND_FLOOR_ATOMIC` from `config/consensus_constants.json`
//! (same JSON authority as C++ / `shekyl-engine-core`; avoids a crate cycle).

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("missing CARGO_MANIFEST_DIR"));
    let config_path = manifest_dir
        .parent()
        .expect("workspace/rust path expected")
        .parent()
        .expect("workspace root path expected")
        .join("config")
        .join("consensus_constants.json");

    println!("cargo:rerun-if-changed={}", config_path.display());

    let raw = fs::read_to_string(&config_path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", config_path.display()));
    let map: BTreeMap<String, serde_json::Value> = serde_json::from_str(&raw)
        .unwrap_or_else(|e| panic!("invalid JSON in {}: {e}", config_path.display()));

    let floor = map
        .get("archival_bond_floor_atomic")
        .and_then(serde_json::Value::as_u64)
        .unwrap_or_else(|| {
            panic!(
                "missing archival_bond_floor_atomic in {}",
                config_path.display()
            )
        });

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("missing OUT_DIR"));
    let out_file = out_dir.join("archival_bond_floor_generated.rs");
    let output = format!(
        "// @generated by build.rs from config/consensus_constants.json — do not edit.\n\
         pub const ARCHIVAL_BOND_FLOOR_ATOMIC: u64 = {floor};\n"
    );
    fs::write(&out_file, output).expect("failed writing archival bond floor constant");
}
