#!/usr/bin/env bash
# Copyright (c) 2026, The Shekyl Foundation
#
# All rights reserved.
# BSD-3-Clause
#
# Run a cargo bench on a remote host and capture its output WITHOUT truncation.
#
# WHY THIS EXISTS
#
# A remote sweep was launched with `cargo bench ... | tail -200`, which silently
# discarded the early cells. Criterion's `estimates.json` happened to survive
# and the run was recoverable -- but a pipeline that DISCARDS rather than FAILS
# is the same class as chaining a gate and a push with `;`, and a sweep that
# lost both would have cost a full re-run on a machine that takes ~14 minutes
# just to build.
#
# The fix is the same shape: capture to a file, and tail the FILE for display,
# so the artifact is never the thing being truncated.
#
# THE SENTINEL DECIDES, IT DOES NOT ANNOUNCE
#
# The operator's contract is `tail` on the log, so the last line is what says
# whether the sweep finished. `BENCH_COMPLETE` is therefore printed ONLY on a
# clean exit, and `BENCH_EXIT=<rc>` is printed unconditionally beside it: a
# sweep that OOMs at cell 40, or panics on a fixture that stopped verifying,
# must not read as a finished one -- that is the `;` class again, one level
# out, and it ends with a partial surface collapsed into a constant.
#
# The `--test` pass is kept and now GATES the timing run (`&&`). It costs a
# second fixture build, and it buys the precondition the round records:
# "verify-check exit 0 -- every depth fixture produced a real proof, so no cell
# is a timing of the reject path" (DAEMON_RELAY_PRIVACY.md §85.1). Dropping it
# would retire a recorded condition to save build time.
#
# USAGE
#   scripts/remote-bench.sh <host> <bench-name> [remote-workspace]
set -euo pipefail
HOST="${1:?usage: $0 <host> <bench> [workspace]}"
BENCH="${2:?usage: $0 <host> <bench> [workspace]}"
WS="${3:-~/shekyl-bench/rust}"
LOG="/tmp/${BENCH}.full.log"
BODY="/tmp/remote-bench-${BENCH}.body.sh"

# The body is SHIPPED AS A FILE rather than interpolated into the ssh command
# string. Two reasons, both bugs that were live in the first version: the login
# shell on the bench host is not guaranteed to be bash (the old launcher used
# `disown`, which is not POSIX), and a body embedded in a remote command line
# has to survive two rounds of quoting -- so a workspace path or bench name
# carrying shell-significant characters became remote syntax. A file survives
# neither problem, and `$WS` / `$BENCH` arrive as positional arguments.
ssh "$HOST" "cat > $BODY" <<'REMOTE'
#!/usr/bin/env bash
# Generated by scripts/remote-bench.sh -- edit there, not on the bench host.
set -uo pipefail
WS="$1"
BENCH="$2"
# `~` is not expanded inside a quoted argument, so the default workspace would
# arrive literal. Expand it here rather than making the caller avoid tildes.
case "$WS" in
"~"*) WS="${HOME}${WS#\~}" ;;
esac
# shellcheck disable=SC1090  # cargo's env, on the bench host
source ~/.cargo/env
cd "$WS" || exit 1
grep -h . /sys/devices/system/cpu/cpu[0-9]*/cpufreq/scaling_governor | sort | uniq -c
# `&&`: the --test pass GATES the timing run. A fixture that stopped verifying
# must stop the sweep, not silently retitle hours of timings as measurements of
# the reject path.
cargo +1.94.0 bench -p shekyl-ffi --bench "$BENCH" -- --test \
	&& cargo +1.94.0 bench -p shekyl-ffi --bench "$BENCH"
rc=$?
echo "BENCH_EXIT=$rc"
[ "$rc" -eq 0 ] && echo BENCH_COMPLETE
exit "$rc"
REMOTE

ssh "$HOST" "setsid nohup bash $BODY $(printf '%q %q' "$WS" "$BENCH") \
  > $LOG 2>&1 < /dev/null & echo launched"

echo "capturing to $HOST:$LOG -- full output, no pipe"
echo "poll:  ssh $HOST 'tail -20 $LOG'"
echo "done when the log ends BENCH_COMPLETE; BENCH_EXIT=<n> alone means it FAILED"
