//! Generate the FCMP++ reference-block age constants from the JSON
//! authority at `config/consensus_constants.json`. The same JSON drives
//! the C++ header generator at `cmake/generate_consensus_constants.py`
//! so the two languages cannot drift.
//!
//! Bug class motivation: Bug 3 of the 2026-05-05 FFI constant-drift
//! audit (`docs/audit_trail/2026-05-ffi-constant-drift-audit.md`), where
//! a hand-defined `FCMP_REFERENCE_BLOCK_MIN_AGE = 10` silently diverged
//! from the consensus value `5` for ~3 weeks. The pattern mirrors
//! `rust/shekyl-engine-core/build.rs` and `rust/shekyl-difficulty/build.rs`;
//! the per-crate `build.rs` (rather than depending on `shekyl-engine-core`
//! for the constants) preserves this crate's lean / leaf-of-the-workspace
//! property — no heavy internal workspace dep just to read two integers
//! (`CURVE_TREE_CLIENT.md` §3.1, `17-dependency-discipline.mdc`).
//!
//! Only the two reference-block ages used by the client's reference-block
//! selection (`reference::REF_ANCHOR_AGE`) and validity-horizon predicates
//! (`reference::REBUILD_AT`, `proof_submittable`, `proof_expired`,
//! `should_reanchor`) are emitted here.

use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn get_u64(map: &BTreeMap<String, serde_json::Value>, key: &str, source: &Path) -> u64 {
    map.get(key)
        .and_then(serde_json::Value::as_u64)
        .unwrap_or_else(|| {
            panic!(
                "missing or invalid u64 key {key:?} in {source}",
                source = source.display()
            )
        })
}

fn main() {
    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("missing CARGO_MANIFEST_DIR"));
    // shekyl-curve-tree lives at rust/shekyl-curve-tree; the workspace
    // JSON authority is two levels up at config/.
    let config_path = manifest_dir
        .parent()
        .expect("workspace/rust path expected")
        .parent()
        .expect("workspace root path expected")
        .join("config")
        .join("consensus_constants.json");

    println!("cargo:rerun-if-changed={}", config_path.display());

    let raw = fs::read_to_string(&config_path)
        .unwrap_or_else(|e| panic!("failed to read {}: {e}", config_path.display()));
    let map: BTreeMap<String, serde_json::Value> = serde_json::from_str(&raw)
        .unwrap_or_else(|e| panic!("invalid JSON in {}: {e}", config_path.display()));

    let min_age = get_u64(&map, "fcmp_reference_block_min_age", &config_path);
    let max_age = get_u64(&map, "fcmp_reference_block_max_age", &config_path);

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("missing OUT_DIR"));
    let out_file = out_dir.join("consensus_constants_generated.rs");

    // Crate-private (no `pub`): the only consumer is `src/reference.rs`,
    // which re-exports them under doc-rich public names and derives
    // `REF_ANCHOR_AGE` / `REBUILD_AT`. Keeping these private prevents
    // downstream consumers depending on the JSON-key-derived names and
    // sidesteps `#![deny(missing_docs)]` on the generated file.
    let output = format!(
        "// @generated by build.rs from config/consensus_constants.json — do not edit.\n\
         //\n\
         // Single source of truth: `config/consensus_constants.json`. The C++\n\
         // header at `shekyl/consensus_constants_generated.h` is emitted from\n\
         // the same JSON by `cmake/generate_consensus_constants.py`.\n\
         const FCMP_REFERENCE_BLOCK_MIN_AGE: u64 = {min_age};\n\
         const FCMP_REFERENCE_BLOCK_MAX_AGE: u64 = {max_age};\n",
    );

    fs::write(&out_file, output).expect("failed writing generated consensus constants");
}
