// Copyright (c) 2026, The Shekyl Foundation
//
// All rights reserved.
// BSD-3-Clause

//! Reference-block selection and proof validity-horizon arithmetic
//! (`docs/design/CURVE_TREE_CLIENT.md` §5).
//!
//! A membership proof is anchored to a *reference block* — a recent
//! block whose header-committed curve-tree root the proof is built
//! against. The daemon accepts a spend iff the reference block's age
//! (`tip − reference_height`) is in `[MIN_AGE, MAX_AGE]`
//! (`shekyl-engine-core`'s `SpendIntent::validate_temporal`, mirrored
//! here). This module owns the wallet-side arithmetic for:
//!
//! 1. **Selecting** the canonical reference height for a fresh proof
//!    (`tip − REF_ANCHOR_AGE`, §5.1). Every honest wallet uses the same
//!    offset — the age is observable on every tx, so a per-wallet offset
//!    would fingerprint the wallet (`00-mission.mdc` priority 2; same
//!    uniformity logic as dust `K_DUST`).
//! 2. **Bounding** how long a built proof stays submittable (the
//!    validity horizon, §5.2) and deciding when to proactively
//!    **re-anchor** an in-flight proof before it expires mid-flight.
//!
//! ## Why arithmetic, not a `ReferenceBlock` constructor
//!
//! [`crate::CurveTreeClient`] does not store block-header roots — the
//! caller supplies the consensus [`crate::ReferenceBlock`] (height +
//! header root) that [`crate::CurveTreeClient::assemble_path`] verifies
//! the reconstructed root against. So reference-block *selection* is
//! height arithmetic the caller drives against its own chain view; this
//! module exposes that arithmetic as total, side-effect-free functions
//! over heights. Binding a height to a consensus root remains the
//! caller's responsibility (the caller-supplies-root integrity model,
//! §3.5). No secrets, no I/O, no chain access here.

// Generated by `build.rs` from `config/consensus_constants.json`:
//   const FCMP_REFERENCE_BLOCK_MIN_AGE: u64
//   const FCMP_REFERENCE_BLOCK_MAX_AGE: u64
// Same JSON authority drives the C++ header, so the wallet's
// acceptance-window view cannot drift from consensus
// (`docs/audit_trail/2026-05-ffi-constant-drift-audit.md`).
include!(concat!(
    env!("OUT_DIR"),
    "/consensus_constants_generated.rs"
));

/// Minimum reference-block age the daemon accepts (`tip − reference_height
/// ≥ MIN_AGE`). Re-exported from the JSON authority under a doc-rich name.
pub const REFERENCE_BLOCK_MIN_AGE: u64 = FCMP_REFERENCE_BLOCK_MIN_AGE;

/// Maximum reference-block age the daemon accepts (`tip − reference_height
/// ≤ MAX_AGE`). Past this the daemon rejects the spend as too stale.
pub const REFERENCE_BLOCK_MAX_AGE: u64 = FCMP_REFERENCE_BLOCK_MAX_AGE;

// Sentinel against silent drift (mirrors `shekyl-engine-core`'s
// `multisig::v31::intent`): a JSON edit that moves these recomputes the
// derived constants below, and these const-evaluated asserts force the
// editor to review the privacy/consensus implications before bumping the
// sentinel rather than letting the change land silently.
const _: () = assert!(
    REFERENCE_BLOCK_MIN_AGE == 5,
    "FCMP_REFERENCE_BLOCK_MIN_AGE diverged from baseline (5); REF_ANCHOR_AGE \
     is privacy-canonical — review §5.1 uniformity before updating the sentinel"
);
const _: () = assert!(
    REFERENCE_BLOCK_MAX_AGE == 100,
    "FCMP_REFERENCE_BLOCK_MAX_AGE diverged from baseline (100); the validity \
     horizon and rebuild threshold derive from it — review §5.2 before updating"
);

/// Canonical age offset for the reference block of a freshly built proof:
/// `reference_height = tip − REF_ANCHOR_AGE` (§5.1).
///
/// `MIN_AGE + 1`, matching the daemon's `get_curve_tree_path` anchor
/// (`top_height − (MIN_AGE + 1)`) so wallet- and daemon-assembled paths
/// agree on the anchor. One block deeper than the bare `MIN_AGE` floor
/// for reorg safety. **Privacy-canonical, not a per-wallet knob:** every
/// honest wallet uses this exact offset so the on-wire reference age does
/// not fingerprint the wallet. Re-derived only on a substrate change
/// (observed depth-6 reorg rate, or a `MIN_AGE` consensus change), not by
/// preference (§5.1 reversion clause).
pub const REF_ANCHOR_AGE: u64 = FCMP_REFERENCE_BLOCK_MIN_AGE + 1;

/// Submittable lifetime of a proof, in blocks, measured from build time
/// (§5.2): `MAX_AGE − REF_ANCHOR_AGE`. Built at `reference_height =
/// tip_build − REF_ANCHOR_AGE`, the proof's reference age crosses
/// `MAX_AGE` after this many blocks, at which point the daemon rejects it
/// as too stale. This is the proactive bound `PHASE_2A_SEND_PATH.md` §9
/// #5 left unbounded in Round 0.
pub const PROOF_VALIDITY_HORIZON: u64 = FCMP_REFERENCE_BLOCK_MAX_AGE - REF_ANCHOR_AGE;

/// Reference-block age at which the wallet proactively re-anchors an
/// in-flight, still-unconfirmed proof rather than risk a too-stale
/// rejection mid-flight (§5.2): `MAX_AGE / 2`. The half-`MAX_AGE` margin
/// leaves room for propagation plus a confirmation attempt.
///
/// **Local wallet-hygiene parameter, not consensus and not
/// privacy-observable** — it changes only *when* a wallet rebuilds, never
/// the on-wire reference age — so, unlike [`REF_ANCHOR_AGE`], it is
/// tunable without a uniformity cost. Pinned with a documented default.
pub const REBUILD_AT: u64 = FCMP_REFERENCE_BLOCK_MAX_AGE / 2;

// Derived-constant sentinels: catch an arithmetic regression if the JSON
// values change in a way the sentinels above were updated to permit.
const _: () = assert!(REF_ANCHOR_AGE == 6);
const _: () = assert!(PROOF_VALIDITY_HORIZON == 94);
const _: () = assert!(REBUILD_AT == 50);

/// The canonical reference height for a proof built at `tip`:
/// `tip − REF_ANCHOR_AGE` (§5.1).
///
/// `None` when `tip < REF_ANCHOR_AGE` — the chain is too short to have a
/// legal reference block. This is the structural pre-maturity window: no
/// non-coinbase output is spendable before the founder allocation matures
/// (`CT2_DRAIN_ORDER.md` §5), so a caller that has a spendable output
/// always has a tip past this floor; the `None` is a total-function
/// guard, not an expected runtime branch.
#[must_use]
pub fn select_reference_height(tip: u64) -> Option<u64> {
    tip.checked_sub(REF_ANCHOR_AGE)
}

/// The age of a reference block as seen from `tip_now`:
/// `tip_now − reference_height`.
///
/// `None` when `reference_height > tip_now` — the reference block is above
/// the current tip, only possible across a reorg that dropped the chain
/// below it (§5.3). Callers treat `None` as "re-anchor required".
#[must_use]
pub fn reference_block_age(tip_now: u64, reference_height: u64) -> Option<u64> {
    tip_now.checked_sub(reference_height)
}

/// Whether a proof anchored at `reference_height` is still within the
/// daemon's acceptance window at `tip_now`: `MIN_AGE ≤ age ≤ MAX_AGE`.
///
/// Mirrors `shekyl-engine-core`'s `SpendIntent::validate_temporal` window
/// (too-fresh below `MIN_AGE`, too-stale above `MAX_AGE`). A reference
/// height above the tip (reorg, age `None`) is not submittable.
#[must_use]
pub fn proof_submittable(tip_now: u64, reference_height: u64) -> bool {
    matches!(
        reference_block_age(tip_now, reference_height),
        Some(age) if (REFERENCE_BLOCK_MIN_AGE..=REFERENCE_BLOCK_MAX_AGE).contains(&age)
    )
}

/// Whether a proof has aged out of the daemon's acceptance window — its
/// reference age exceeds `MAX_AGE` (the validity horizon), so the daemon
/// will reject it as too stale.
///
/// `true` also when the reference block is above the tip (age `None`,
/// reorg §5.3): the anchor is no longer on the chain, so the proof cannot
/// be submitted as-is. Distinct from "too fresh" (age below `MIN_AGE`),
/// which is not expiry and cannot arise for a wallet-built proof (built
/// at age [`REF_ANCHOR_AGE`]).
#[must_use]
pub fn proof_expired(tip_now: u64, reference_height: u64) -> bool {
    match reference_block_age(tip_now, reference_height) {
        Some(age) => age > REFERENCE_BLOCK_MAX_AGE,
        None => true,
    }
}

/// Whether the wallet should proactively re-anchor an in-flight,
/// still-unconfirmed proof (§5.2): its reference age has reached
/// [`REBUILD_AT`], or the reference block is no longer on the chain
/// (age `None`, reorg §5.3).
///
/// This is the proactive companion to the reactive `ProofStale` signal
/// (2A §3.6): reactive catches a root that went stale unexpectedly; this
/// keeps the wallet from carrying a proof until it hits the hard
/// [`proof_expired`] boundary. In the age-based path, because
/// `REBUILD_AT < MAX_AGE`, `should_reanchor` fires strictly before
/// [`proof_expired`]; in the reorg path (reference above the tip, age
/// `None`) both fire together — the anchor is gone, so re-anchor and
/// expiry coincide.
#[must_use]
pub fn should_reanchor(tip_now: u64, reference_height: u64) -> bool {
    match reference_block_age(tip_now, reference_height) {
        Some(age) => age >= REBUILD_AT,
        None => true,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn derived_constants_match_spec() {
        // §5.1/§5.2 worked example, pinned independently of the
        // const-eval sentinels so a test run also reports the value.
        assert_eq!(REF_ANCHOR_AGE, 6);
        assert_eq!(PROOF_VALIDITY_HORIZON, 94);
        assert_eq!(REBUILD_AT, 50);
        // Horizon is the distance from the build-time age to the cap.
        assert_eq!(
            PROOF_VALIDITY_HORIZON,
            REFERENCE_BLOCK_MAX_AGE - REF_ANCHOR_AGE
        );
        // Re-anchor strictly precedes hard expiry.
        const { assert!(REBUILD_AT < REFERENCE_BLOCK_MAX_AGE) };
    }

    #[test]
    fn select_reference_height_is_tip_minus_anchor() {
        assert_eq!(select_reference_height(1_000), Some(994));
        // Exactly at the floor: tip == REF_ANCHOR_AGE → reference height 0.
        assert_eq!(select_reference_height(REF_ANCHOR_AGE), Some(0));
    }

    #[test]
    fn select_reference_height_none_in_pre_maturity_window() {
        // Tip below the anchor: no legal reference block yet.
        assert_eq!(select_reference_height(REF_ANCHOR_AGE - 1), None);
        assert_eq!(select_reference_height(0), None);
    }

    #[test]
    fn fresh_proof_is_submittable_and_not_expired() {
        let tip = 1_000;
        let r = select_reference_height(tip).unwrap();
        assert_eq!(reference_block_age(tip, r), Some(REF_ANCHOR_AGE));
        assert!(proof_submittable(tip, r));
        assert!(!proof_expired(tip, r));
        assert!(!should_reanchor(tip, r));
    }

    #[test]
    fn acceptance_window_boundaries() {
        // Build the reference height so age == target exactly.
        let tip = 1_000;
        let at = |age: u64| tip - age;

        // Too fresh: age below MIN_AGE is not submittable (cannot arise
        // for a wallet-built proof, but the predicate is total).
        assert!(!proof_submittable(tip, at(REFERENCE_BLOCK_MIN_AGE - 1)));
        // MIN_AGE and MAX_AGE inclusive bounds are submittable.
        assert!(proof_submittable(tip, at(REFERENCE_BLOCK_MIN_AGE)));
        assert!(proof_submittable(tip, at(REFERENCE_BLOCK_MAX_AGE)));
        // One past MAX_AGE is expired, not submittable.
        assert!(!proof_submittable(tip, at(REFERENCE_BLOCK_MAX_AGE + 1)));
        assert!(proof_expired(tip, at(REFERENCE_BLOCK_MAX_AGE + 1)));
        assert!(!proof_expired(tip, at(REFERENCE_BLOCK_MAX_AGE)));
    }

    #[test]
    fn reanchor_fires_at_threshold_before_expiry() {
        let tip = 10_000;
        let at = |age: u64| tip - age;

        assert!(!should_reanchor(tip, at(REBUILD_AT - 1)));
        assert!(should_reanchor(tip, at(REBUILD_AT)));
        // Still submittable at the rebuild threshold (proactive, not a
        // hard bound): re-anchor fires well before expiry.
        assert!(proof_submittable(tip, at(REBUILD_AT)));
        assert!(!proof_expired(tip, at(REBUILD_AT)));
    }

    #[test]
    fn proof_aging_progression() {
        // Walk a single proof's reference age from build to expiry and
        // assert each predicate flips at its documented boundary.
        let reference_height = 10_000;
        for age in 0..=(REFERENCE_BLOCK_MAX_AGE + 5) {
            let tip_now = reference_height + age;
            assert_eq!(
                proof_submittable(tip_now, reference_height),
                (REFERENCE_BLOCK_MIN_AGE..=REFERENCE_BLOCK_MAX_AGE).contains(&age),
                "submittable mismatch at age {age}"
            );
            assert_eq!(
                proof_expired(tip_now, reference_height),
                age > REFERENCE_BLOCK_MAX_AGE,
                "expired mismatch at age {age}"
            );
            assert_eq!(
                should_reanchor(tip_now, reference_height),
                age >= REBUILD_AT,
                "reanchor mismatch at age {age}"
            );
        }
    }

    #[test]
    fn reorg_below_reference_requires_reanchor() {
        // Reference block above the current tip: chain reorged below it.
        let reference_height = 1_000;
        let tip_now = 998;
        assert_eq!(reference_block_age(tip_now, reference_height), None);
        assert!(!proof_submittable(tip_now, reference_height));
        assert!(proof_expired(tip_now, reference_height));
        assert!(should_reanchor(tip_now, reference_height));
    }
}
