// Copyright (c) 2026, The Shekyl Foundation
//
// All rights reserved.
// BSD-3-Clause

//! Subtree-aligned segment math for the CT-1 `LeafStore` hot path.
//!
//! Segment boundaries, freeze eligibility, and `R_k` extraction mirror the
//! CT-0 gate harness (`rust/shekyl-fcmp/tests/curve_tree_freeze.rs`) and are
//! pinned in `docs/design/CT1_ROUND1_PINS.md`.

use shekyl_consensus::DEFAULT_LOCK_WINDOW;
use shekyl_fcmp::tree::{try_build_layers, SCALARS_PER_LEAF};

/// Sub-root layer index `j` for segment boundaries — re-exported from
/// [`shekyl_fcmp::tree`], which owns the partition (the one home; see the
/// module comment there). This crate's `LeafStore` partitions by it and the
/// consensus reader in `shekyl-archival-retention` asserts its
/// `SEGMENT_LEAF_COUNT` against it; neither restates it.
pub use shekyl_fcmp::tree::SEGMENT_LAYER_J;

include!(concat!(env!("OUT_DIR"), "/segment_constants_generated.rs"));

/// Reorg margin a segment's last block must be buried by before the segment
/// freezes (`segment_freeze_eligible`).
///
/// **Is** `ARCHIVAL_REORG_DEPTH_BLOCKS`: generated by this crate's `build.rs`
/// from the same `config/consensus_constants.json` key
/// (`archival_reorg_depth_blocks`) that `shekyl-archival-retention` generates
/// its constant from, so the freeze depth, the bond assembly window, the pass
/// anchor and SO-D8e's fork analysis cannot move apart — a segment frozen and
/// served inside the depth the rest of the system treats as reorg-able was the
/// hazard. This crate cannot import the retention crate's constant (the
/// dependency runs the other way), so the tie is one JSON source rather than
/// an assert. *SUPERSEDED 2026-09-18: the hand-written `720` "until PHASE_2B
/// codegen" (CT-1 dedup, `docs/completed/CT1_ROUND1_PINS.md`).*
pub const SEGMENT_FREEZE_REORG_MARGIN_BLOCKS: u64 = ARCHIVAL_REORG_DEPTH_BLOCKS;

/// Output maturity / spendable age in blocks (`CRYPTONOTE_DEFAULT_TX_SPENDABLE_AGE`).
pub const SPENDABLE_AGE_BLOCKS: u64 = DEFAULT_LOCK_WINDOW as u64;

/// **`W`** — the depth at which the wallet's persisted state is final.
///
/// A segment freezes once it is this old ([`segment_freeze_eligible`]), so a
/// reorg **shallower** than `W` never touches frozen state and needs no undo
/// log (`WALLET_SIDE_STORE.md` §6.3.2 row 2), while a reorg **deeper** than
/// `W` would have to unmake something already sealed.
///
/// **The refusal is not here.** [`crate::LeafStore::rollback_to_fork`]
/// deliberately *permits* a deep truncation — F9 requires it to drop the
/// freeze records correctly, and the replica generator forks arbitrarily deep
/// on purpose. `CT-6` C7 is a policy about whether a **wallet refresh** may
/// ask for one, and it is enforced in the engine
/// (`engine::merge::validate_reorg_within_finality`). The store must do it
/// right; the wallet must never ask.
///
/// Summed from its two owners rather than written as `730`, and named here
/// because three places needed the sum: the freeze gate below, the C7 refusal,
/// and the bench's replay window. A quantity three readers derive
/// independently is one that drifts.
pub const FINALITY_DEPTH_BLOCKS: u64 = SPENDABLE_AGE_BLOCKS + SEGMENT_FREEZE_REORG_MARGIN_BLOCKS;

// The snapshot ring's horizon must sit strictly inside `W`, because the band
// between them is where a rollback is past the ring yet still repairable by
// folding (`CT-6` §10.3). If the two ever met, C7's refusal would swallow that
// band and turn a correct recovery into a re-sync.
const _: () = assert!(SEGMENT_FREEZE_REORG_MARGIN_BLOCKS < FINALITY_DEPTH_BLOCKS);

/// Width of one stored leaf, in bytes.
///
/// Derived from the leaf's scalar content rather than written as `128`: a
/// leaf **is** `SCALARS_PER_LEAF` Selene scalars, so the byte width is that
/// fact times the scalar width, not an independent number that has to be
/// kept in step ([rule 17](../../../.cursor/rules/17-dependency-discipline.mdc)).
/// The `LEAVES_TABLE` value type (`&[u8; 128]`) is the persisted layout;
/// this is the same width where a `usize` is wanted rather than a type, and
/// the assertion below is what keeps the two from parting company.
pub const LEAF_BYTES: usize = SCALARS_PER_LEAF * 32;

const _: () = assert!(LEAF_BYTES == 128);

/// Dense segment identifier (`SegmentId` 0 covers tree positions `[0, E)`).
#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Debug)]
pub struct SegmentId(pub u32);

crate::types::redb_delegated_key!(SegmentId, u32, "shekyl_curve_tree::SegmentId");

/// Segment size `E` at layer `j`, and the pinned segment size — re-exported
/// from [`shekyl_fcmp::tree`] (the one home for the partition).
pub use shekyl_fcmp::tree::{leaves_per_segment, outputs_per_node};

/// Height-based freeze gate (`CT1_ROUND1_PINS.md`).
#[must_use]
pub fn segment_freeze_eligible(tip_height: u64, end_block_height: u64) -> bool {
    tip_height.saturating_sub(end_block_height) >= FINALITY_DEPTH_BLOCKS
}

/// Recompute segment `k`'s sub-root `R_k` from its `E` leaf scalars.
pub fn extract_r_k(leaf_scalars: &[[u8; 32]]) -> [u8; 32] {
    try_extract_r_k(leaf_scalars).expect("valid leaf scalars")
}

/// Fallible [`extract_r_k`] for persisted bytes on the CT-1 store path.
pub fn try_extract_r_k(leaf_scalars: &[[u8; 32]]) -> Option<[u8; 32]> {
    let layers = try_build_layers(leaf_scalars)?;
    layers
        .get(usize::from(SEGMENT_LAYER_J))
        .and_then(|layer| layer.first().copied())
}

/// Flatten `LeafEntry`-style 128-byte leaves into Selene scalars for `build_layers`.
#[must_use]
pub fn leaf_bytes_to_scalars(leaves: &[[u8; 128]]) -> Vec<[u8; 32]> {
    // Each 128-byte leaf yields exactly `SCALARS_PER_LEAF` (4) 32-byte scalars;
    // `LEAF_CHUNK_SCALARS` is per Selene *chunk* and would over-reserve by
    // `SELENE_CHUNK_WIDTH`x on large leaf sets.
    let mut scalars = Vec::with_capacity(leaves.len() * SCALARS_PER_LEAF);
    for leaf in leaves {
        for chunk in leaf.chunks_exact(32) {
            let mut s = [0u8; 32];
            s.copy_from_slice(chunk);
            scalars.push(s);
        }
    }
    scalars
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn freeze_gate_requires_height_burial() {
        let margin = SPENDABLE_AGE_BLOCKS + SEGMENT_FREEZE_REORG_MARGIN_BLOCKS;
        assert!(!segment_freeze_eligible(margin - 1, 0));
        assert!(segment_freeze_eligible(margin, 0));
        assert!(!segment_freeze_eligible(margin, 1));
    }
}
