# Copyright (c) 2026, The Shekyl Foundation
#
# All rights reserved.
# BSD-3-Clause
#
# The NNhfs pattern, the walk that emits it, and the claims pinned against
# it. An edit drops a token. A break replaces one primitive's output with
# the public constant in lib/noise.pvl. A property that holds names the row
# that must make it fail. run.py is the thing that executes the result.

from __future__ import annotations

import enum
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
LIB = HERE.parent / "lib" / "noise.pvl"
VARIANTS = HERE / "variants"

# The nonce family noise.pvl declares. A seal takes the next one; MixKey
# starts again at n0. NNhfs uses n0 and n1. n2 stays for a later handshake
# that seals three times under one key (hybridXK), so using it is not a
# new declaration.
NONCES = ("n0", "n1", "n2")

HEADER = """(* ---- generated by docs/formal/proverif/nnhfs/run.py; do not edit ----
   Variant:  {name}
   Scenario: {scenario}
   Edits:    {edits}
   Breaks:   {breaks}
   PWD-T1 Noise_NNhfs. The walk follows the pattern; an edit drops a token.
   Load with: proverif -lib docs/formal/proverif/lib/noise.pvl <this file> *)

free c: channel.
(* The honest pair's link under a passive attacker. Every message that
   crosses it is also written to c, so the attacker reads all and injects
   nothing. The active scenario uses c for the link too. *)
free hs: channel [private].

const protocol_name: bitstring.
(* Network ids are public: the first 16 bytes of
   cSHAKE256(S = NETWORK_ID_DST, X = genesis block hash)
   (prefix.rs, network_id_from_genesis). Two of them, so a handshake
   across networks can be asked about. *)
free nidA: bitstring.
free nidB: bitstring.

(* The first transport bodies. Secret unless the handshake leaks them.
   body_len is the public 2-byte length header (channel.rs). *)
free req0: bitstring [private].
free rep0: bitstring [private].
free req1: bitstring [private].
free rep1: bitstring [private].
const body_len: bitstring.
const len_ad: bitstring.
const body_ad: bitstring.

(* (network id, k_i2r, k_r2i): the Split keys a role ends with. *)
event InitiatorDone(bitstring, key, key).
event ResponderDone(bitstring, key, key).
"""


class Role(enum.Enum):
    INITIATOR = "Initiator"
    RESPONDER = "Responder"


class Token(enum.Enum):
    """One Noise token. The walk, not the caller, knows what the token does."""

    E = "e"  # DH ephemeral public, then MixHash
    EK = "ek"  # ML-KEM encapsulation key, in the clear, then MixHash
    EE = "ee"  # MixKey of the X25519 shared secret
    EKEM = "ekem"  # encapsulate, EncryptAndHash the ciphertext, MixKey the secret


class Edit(enum.Enum):
    NO_EKEM = "no_ekem"
    NO_EE = "no_ee"
    NO_PROLOGUE = "no_prologue"
    REUSE_EPH = "reuse_eph"


class Break(enum.Enum):
    DH = "dh"
    KEM = "kem"


class Scenario(enum.Enum):
    PASSIVE = "passive"
    ACTIVE = "active"
    CROSS = "cross"
    LATER_EPH = "later_eph"
    OWN_EPH = "own_eph"


class Verdict(enum.Enum):
    """ProVerif's two pinned answers. HOLDS is "is true": a secret stays
    secret, or an event conjunction is unreachable."""

    HOLDS = "true"
    FAILS = "false"


class Message:
    """One handshake message. The payload is hashed. It is sent only when
    `transmit_payload` is set: message 1 has no key, so the empty payload
    is mixed and not put on the wire (noise.rs)."""

    def __init__(self, sender: Role, tokens: tuple[Token, ...], transmit_payload: bool):
        self.sender = sender
        self.tokens = tokens
        self.transmit_payload = transmit_payload


# PWD-T1. Message 1 is `e, ek`. Message 2 is `e, ee, ekem`, then the empty payload.
PATTERN = (
    Message(Role.INITIATOR, (Token.E, Token.EK), transmit_payload=False),
    Message(Role.RESPONDER, (Token.E, Token.EE, Token.EKEM), transmit_payload=True),
)


def dropped_tokens(edits: frozenset[Edit]) -> frozenset[Token]:
    gone: set[Token] = set()
    if Edit.NO_EE in edits:
        gone.add(Token.EE)
    if Edit.NO_EKEM in edits:
        gone.add(Token.EKEM)
    return frozenset(gone)


def leak_prefix(scenario: Scenario) -> str:
    """A session that already runs in phase 1 cannot enter phase 1 again."""
    if scenario is Scenario.LATER_EPH:
        return ""
    return "phase 1; "


class Sym:
    """Symbolic symmetric state, advanced the way noise.rs `Sym` advances.

    `h0`/`ck0` are the prologue. Each MixHash allocates the next `hN`.
    Each MixKey allocates the next `ckN` and `kN` and restarts the nonce
    at `n0`.
    """

    def __init__(self) -> None:
        self.lines: list[str] = []
        self.h = "h0"
        self.h_n = 0
        self.ck = "ck0"
        self.ck_n = 0
        self.key: str | None = None
        self.key_n = 0
        self.nonce = 0
        self.has_key = False

    def line(self, text: str) -> None:
        self.lines.append(f"  {text}")

    def _alloc_h(self) -> str:
        self.h_n += 1
        return f"h{self.h_n}"

    def mix_hash(self, data: str) -> None:
        nxt = self._alloc_h()
        self.line(f"let {nxt} = mixh({self.h}, {data}) in")
        self.h = nxt

    def mix_key(self, ikm: str) -> None:
        previous = self.ck
        self.ck_n += 1
        self.key_n += 1
        self.ck = f"ck{self.ck_n}"
        self.key = f"k{self.key_n}"
        self.nonce = 0
        self.has_key = True
        self.line(f"let {self.ck} = kdfck({previous}, {ikm}) in")
        self.line(f"let {self.key} = kdfk({previous}, {ikm}) in")

    def _nonce(self) -> str:
        if self.nonce >= len(NONCES):
            raise RuntimeError(
                f"a key used {self.nonce + 1} seals; noise.pvl declares {len(NONCES)}"
            )
        name = NONCES[self.nonce]
        self.nonce += 1
        return name

    def seal(self, plaintext: str, ciphertext: str) -> str:
        """EncryptAndHash. With no key, MixHash the plaintext and send it."""
        if not self.has_key:
            self.line(f"let {ciphertext} = {plaintext} in")
            self.mix_hash(ciphertext)
            return ciphertext
        nxt = self._alloc_h()
        self.line(
            f"let ({ciphertext}: bitstring, {nxt}: bitstring) = "
            f"eah({self.key}, {self._nonce()}, {self.h}, {plaintext}) in"
        )
        self.h = nxt
        return ciphertext

    def open_seal(self, ciphertext: str, pattern: str) -> None:
        """DecryptAndHash. With no key, the ciphertext is the plaintext."""
        if not self.has_key:
            # `=empty` is an equality pattern and needs parentheses.
            # `ct2b(ct)` is a type-converter pattern and must not be a tuple.
            written = f"({pattern})" if pattern.startswith("=") else pattern
            self.line(f"let {written} = {ciphertext} in")
            self.mix_hash(ciphertext)
            return
        nxt = self._alloc_h()
        self.line(
            f"let ({pattern}, {nxt}: bitstring) = "
            f"dah({self.key}, {self._nonce()}, {self.h}, {ciphertext}) in"
        )
        self.h = nxt


def _tuple(parts: list[str]) -> str:
    if len(parts) == 1:
        return parts[0]
    return "(" + ", ".join(parts) + ")"


class Walk:
    """Emit one role by walking PATTERN. Write and read are the two
    directions of the same token."""

    def __init__(self, role: Role, edits: frozenset[Edit], breaks: frozenset[Break]):
        self.role = role
        self.edits = edits
        self.breaks = breaks
        self.sym = Sym()
        payload = "req" if role is Role.INITIATOR else "rep"
        self.sym.lines.append(
            f"let {role.value}(nid: bitstring, link: channel, {payload}: bitstring, leak: bool) ="
        )

    def emit(self, scenario: Scenario) -> str:
        self._prologue()
        skip = dropped_tokens(self.edits)
        for message in PATTERN:
            tokens = tuple(token for token in message.tokens if token not in skip)
            self._message(message, tokens)
        self._split_records_and_leak(leak_prefix(scenario))
        return "\n".join(self.sym.lines)

    def _prologue(self) -> None:
        self.sym.line("let ck0 = hinit(protocol_name) in")
        if Edit.NO_PROLOGUE in self.edits:
            self.sym.line("let h0 = hinit(protocol_name) in")
        else:
            self.sym.line("let h0 = mixh(hinit(protocol_name), nid) in")

    def _message(self, message: Message, tokens: tuple[Token, ...]) -> None:
        names = ", ".join(token.value for token in tokens) or "no tokens"
        self.sym.line(f"(* {names} *)")
        if message.sender is self.role:
            parts: list[str] = []
            for token in tokens:
                part = self._write(token)
                if part is not None:
                    parts.append(part)
            if message.transmit_payload:
                parts.append(self.sym.seal("empty", "tag"))
            else:
                self.sym.mix_hash("empty")
            wire = _tuple(parts)
            self.sym.line(f"out(link, {wire});")
            self.sym.line(f"out(c, {wire});")
            return
        binds: list[str] = []
        for token in tokens:
            bind = self._read_bind(token)
            if bind is not None:
                binds.append(bind)
        if message.transmit_payload:
            binds.append("tag: bitstring")
        self.sym.line(f"in(link, {_tuple(binds)});")
        for token in tokens:
            self._read(token)
        if message.transmit_payload:
            self.sym.open_seal("tag", "=empty")
        else:
            self.sym.mix_hash("empty")

    def _write(self, token: Token) -> str | None:
        if token is Token.E:
            return self._write_e()
        if token is Token.EK:
            return self._write_ek()
        if token is Token.EE:
            self._mix_ee()
            return None
        if token is Token.EKEM:
            return self._write_ekem()
        raise RuntimeError(f"unknown token {token}")

    def _read(self, token: Token) -> None:
        if token is Token.E:
            point = "re" if self.role is Role.INITIATOR else "ie"
            self.sym.mix_hash(f"p2b({point})")
            return
        if token is Token.EK:
            self.sym.mix_hash("kpk2b(iek)")
            return
        if token is Token.EE:
            self._mix_ee()
            return
        if token is Token.EKEM:
            self._read_ekem()
            return
        raise RuntimeError(f"unknown token {token}")

    def _read_bind(self, token: Token) -> str | None:
        if token is Token.E:
            return "re: point" if self.role is Role.INITIATOR else "ie: point"
        if token is Token.EK:
            return "iek: kempk"
        if token is Token.EE:
            return None
        if token is Token.EKEM:
            return "cct: bitstring"
        raise RuntimeError(f"unknown token {token}")

    def _write_e(self) -> str:
        if self.role is Role.INITIATOR:
            if Edit.REUSE_EPH in self.edits:
                self.sym.line("let ei = ei_shared in")
            else:
                self.sym.line("new ei: scalar;")
            self.sym.line("let epub = exp(g, ei) in")
            self.sym.mix_hash("p2b(epub)")
            return "epub"
        self.sym.line("new er: scalar;")
        self.sym.line("let repub = exp(g, er) in")
        self.sym.mix_hash("p2b(repub)")
        return "repub"

    def _write_ek(self) -> str:
        if Edit.REUSE_EPH in self.edits:
            self.sym.line("let eki = eki_shared in")
        else:
            self.sym.line("new eki: kemsk;")
        self.sym.line("let ekpub = kpk(eki) in")
        self.sym.mix_hash("kpk2b(ekpub)")
        return "ekpub"

    def _mix_ee(self) -> None:
        if self.role is Role.INITIATOR:
            shared = "broken_dh" if Break.DH in self.breaks else "exp(re, ei)"
        else:
            shared = "broken_dh" if Break.DH in self.breaks else "exp(ie, er)"
        self.sym.line(f"let dh = {shared} in")
        self.sym.mix_key("p2b(dh)")

    def _write_ekem(self) -> str:
        self.sym.line("new r: seed;")
        self.sym.line("let ct = kct(iek, r) in")
        secret = "broken_kem" if Break.KEM in self.breaks else "kss(iek, r)"
        self.sym.line(f"let ss = {secret} in")
        ciphertext = self.sym.seal("ct2b(ct)", "cct")
        self.sym.mix_key("ss")
        return ciphertext

    def _read_ekem(self) -> None:
        if self.sym.has_key:
            self.sym.open_seal("cct", "ctb: bitstring")
            self.sym.line("let ct2b(ct) = ctb in")
        else:
            self.sym.open_seal("cct", "ct2b(ct)")
        secret = "broken_kem" if Break.KEM in self.breaks else "kdecaps(ct, eki)"
        self.sym.line(f"let ss = {secret} in")
        self.sym.mix_key("ss")

    def _split_records_and_leak(self, prefix: str) -> None:
        ck = self.sym.ck
        self.sym.line(f"let k_i2r = split1({ck}) in")
        self.sym.line(f"let k_r2i = split2({ck}) in")
        self.sym.line(f"event {self.role.value}Done(nid, k_i2r, k_r2i);")
        self.sym.line("(* length under len_ad at n0, body under body_ad at n1 *)")
        if self.role is Role.INITIATOR:
            self.sym.line("let req_len = aead(k_i2r, n0, len_ad, body_len) in")
            self.sym.line("let req_body = aead(k_i2r, n1, body_ad, req) in")
            self.sym.line("out(link, (req_len, req_body));")
            self.sym.line("out(c, (req_len, req_body));")
            self.sym.line("in(link, (rep_len: bitstring, rep_body: bitstring));")
            self.sym.line("let (=body_len) = adec(k_r2i, n0, len_ad, rep_len) in")
            self.sym.line("let reply = adec(k_r2i, n1, body_ad, rep_body) in")
            self.sym.line(f"(if leak then {prefix}out(c, (ei, eki))).")
            return
        self.sym.line("in(link, (req_len: bitstring, req_body: bitstring));")
        self.sym.line("let (=body_len) = adec(k_i2r, n0, len_ad, req_len) in")
        self.sym.line("let request = adec(k_i2r, n1, body_ad, req_body) in")
        self.sym.line("let rep_len = aead(k_r2i, n0, len_ad, body_len) in")
        self.sym.line("let rep_body = aead(k_r2i, n1, body_ad, rep) in")
        self.sym.line("out(link, (rep_len, rep_body));")
        self.sym.line("out(c, (rep_len, rep_body));")
        self.sym.line(f"(if leak then {prefix}out(c, er)).")


QUERIES = {
    "req_secret": "query attacker(req0).",
    "rep_secret": "query attacker(rep0).",
    "req_secret_p1": "query attacker(req0) phase 1.",
    "rep_secret_p1": "query attacker(rep0) phase 1.",
    "key_secret_i2r": (
        "query n: bitstring, k1: key, k2: key;\n"
        "  event(InitiatorDone(n, k1, k2)) && attacker(k1)."
    ),
    "key_secret_r2i": (
        "query n: bitstring, k1: key, k2: key;\n"
        "  event(InitiatorDone(n, k1, k2)) && attacker(k2)."
    ),
    "cross_network": (
        "query k1: key, k2: key;\n"
        "  event(InitiatorDone(nidA, k1, k2)) && event(ResponderDone(nidB, k1, k2))."
    ),
    # Not a secrecy claim. This must FAIL (the events are reachable), or
    # every secrecy claim is true of a handshake that cannot finish.
    "reach_pair": (
        "query k1: key, k2: key;\n"
        "  event(InitiatorDone(nidA, k1, k2)) && event(ResponderDone(nidA, k1, k2))."
    ),
}

MAINS = {
    Scenario.PASSIVE: """process
  ( !Initiator(nidA, hs, req0, false) | !Responder(nidA, hs, rep0, false) )
""",
    Scenario.ACTIVE: """process
  ( !Initiator(nidA, c, req0, false) | !Responder(nidA, c, rep0, false) )
""",
    Scenario.CROSS: """process
  ( !Initiator(nidA, hs, req0, false) | !Responder(nidA, hs, rep0, false)
  | !Initiator(nidB, hs, req1, false) | !Responder(nidB, hs, rep1, false) )
""",
    # The phase-0 session keeps its ephemerals. The phase-1 sessions
    # publish theirs once they finish. That is session independence:
    # later ephemerals, not this session's, and not forward secrecy.
    Scenario.LATER_EPH: """process
  ( Initiator(nidA, hs, req0, false) | Responder(nidA, hs, rep0, false)
  | ( phase 1; ( !Initiator(nidA, hs, req1, true) | !Responder(nidA, hs, rep1, true) ) ) )
""",
    Scenario.OWN_EPH: """process
  ( Initiator(nidA, hs, req0, true) | Responder(nidA, hs, rep0, true) )
""",
}

Expects = tuple[tuple[str, Verdict], ...]


class Row:
    """One executed model: a scenario, the edits and breaks applied, and
    the verdict of each query, in the order ProVerif reports them."""

    def __init__(
        self,
        name: str,
        scenario: Scenario,
        edits: frozenset[Edit],
        breaks: frozenset[Break],
        expects: Expects,
    ):
        self.name = name
        self.scenario = scenario
        self.edits = edits
        self.breaks = breaks
        self.expects = expects


class Claim:
    """A property and, when it holds, the row that must flip it.
    A stated non-property has no falsifier: its own verdict is the failure."""

    def __init__(self, row: Row, falsifier: Row | None):
        self.row = row
        self.falsifier = falsifier


def _secrecy(reach: bool) -> Expects:
    rows: list[tuple[str, Verdict]] = [
        ("req_secret", Verdict.HOLDS),
        ("rep_secret", Verdict.HOLDS),
        ("key_secret_i2r", Verdict.HOLDS),
        ("key_secret_r2i", Verdict.HOLDS),
    ]
    if reach:
        rows.append(("reach_pair", Verdict.FAILS))
    return tuple(rows)


def _secrecy_fails() -> Expects:
    return (
        ("req_secret", Verdict.FAILS),
        ("rep_secret", Verdict.FAILS),
        ("key_secret_i2r", Verdict.FAILS),
        ("key_secret_r2i", Verdict.FAILS),
        ("reach_pair", Verdict.FAILS),
    )


def _later(holds: bool) -> Expects:
    verdict = Verdict.HOLDS if holds else Verdict.FAILS
    return (("req_secret_p1", verdict), ("rep_secret_p1", verdict))


CLAIMS = (
    Claim(
        Row("passive", Scenario.PASSIVE, frozenset(), frozenset(), _secrecy(True)),
        Row(
            "edit_no_ee_no_ekem",
            Scenario.PASSIVE,
            frozenset({Edit.NO_EE, Edit.NO_EKEM}),
            frozenset(),
            _secrecy_fails(),
        ),
    ),
    Claim(
        Row("hybrid_dh_broken", Scenario.PASSIVE, frozenset(), frozenset({Break.DH}), _secrecy(True)),
        Row(
            "edit_no_ekem_dh_broken",
            Scenario.PASSIVE,
            frozenset({Edit.NO_EKEM}),
            frozenset({Break.DH}),
            _secrecy_fails(),
        ),
    ),
    Claim(
        Row(
            "hybrid_kem_broken",
            Scenario.PASSIVE,
            frozenset(),
            frozenset({Break.KEM}),
            _secrecy(True),
        ),
        Row(
            "edit_no_ee_kem_broken",
            Scenario.PASSIVE,
            frozenset({Edit.NO_EE}),
            frozenset({Break.KEM}),
            _secrecy_fails(),
        ),
    ),
    Claim(
        Row(
            "independent_of_later_ephemerals",
            Scenario.LATER_EPH,
            frozenset(),
            frozenset(),
            _later(True),
        ),
        Row(
            "edit_reuse_ephemeral",
            Scenario.LATER_EPH,
            frozenset({Edit.REUSE_EPH}),
            frozenset(),
            _later(False),
        ),
    ),
    Claim(
        Row(
            "network_binding",
            Scenario.CROSS,
            frozenset(),
            frozenset(),
            (("cross_network", Verdict.HOLDS), ("reach_pair", Verdict.FAILS)),
        ),
        Row(
            "edit_no_prologue",
            Scenario.CROSS,
            frozenset({Edit.NO_PROLOGUE}),
            frozenset(),
            (("cross_network", Verdict.FAILS), ("reach_pair", Verdict.FAILS)),
        ),
    ),
    Claim(
        Row(
            "active_mitm",
            Scenario.ACTIVE,
            frozenset(),
            frozenset(),
            (
                ("req_secret", Verdict.FAILS),
                ("rep_secret", Verdict.FAILS),
                ("reach_pair", Verdict.FAILS),
            ),
        ),
        None,
    ),
    Claim(
        Row(
            "both_broken",
            Scenario.PASSIVE,
            frozenset(),
            frozenset({Break.DH, Break.KEM}),
            (("req_secret", Verdict.FAILS), ("rep_secret", Verdict.FAILS)),
        ),
        None,
    ),
    Claim(
        Row("own_ephemerals_exposed", Scenario.OWN_EPH, frozenset(), frozenset(), _later(False)),
        None,
    ),
)


def rows_of(claims: tuple[Claim, ...]) -> list[Row]:
    out: list[Row] = []
    for claim in claims:
        out.append(claim.row)
        if claim.falsifier is not None:
            out.append(claim.falsifier)
    return out


def check_claims(claims: tuple[Claim, ...]) -> None:
    """A held query with no row that flips it is a vacuous gate."""
    if not claims:
        sys.exit("run.py: no claims")
    seen: set[str] = set()
    for claim in claims:
        row = claim.row
        _check_row(row, seen)
        held = {name for name, verdict in row.expects if verdict is Verdict.HOLDS}
        falsifier = claim.falsifier
        if not held:
            if falsifier is not None:
                sys.exit(f"run.py: {row.name} is a stated non-property and names a falsifier")
            continue
        if falsifier is None:
            sys.exit(f"run.py: {row.name} holds {sorted(held)} and names no falsifier")
        _check_row(falsifier, seen)
        if falsifier.scenario is not row.scenario:
            sys.exit(f"run.py: {falsifier.name} is not the {row.scenario.value} scenario")
        if falsifier.edits == row.edits and falsifier.breaks == row.breaks:
            sys.exit(f"run.py: {falsifier.name} changes neither edits nor breaks")
        flipped = {name for name, verdict in falsifier.expects if verdict is Verdict.FAILS}
        missing = held - flipped
        if missing:
            sys.exit(f"run.py: {falsifier.name} does not flip {sorted(missing)}")


def _check_row(row: Row, seen: set[str]) -> None:
    if row.name in seen:
        sys.exit(f"run.py: duplicate variant {row.name}")
    seen.add(row.name)
    if not row.expects:
        sys.exit(f"run.py: {row.name} has no queries")
    names = [name for name, _ in row.expects]
    if len(names) != len(set(names)):
        sys.exit(f"run.py: {row.name} repeats a query")
    unknown = [name for name in names if name not in QUERIES]
    if unknown:
        sys.exit(f"run.py: {row.name} names unknown queries {unknown}")


def _labels(items: frozenset[enum.Enum]) -> str:
    return ", ".join(sorted(item.value for item in items)) or "none"


def render(row: Row) -> str:
    text = HEADER.format(
        name=row.name,
        scenario=row.scenario.value,
        edits=_labels(row.edits),
        breaks=_labels(row.breaks),
    )
    text += "\n"
    if Edit.REUSE_EPH in row.edits:
        text += "free ei_shared: scalar [private].\nfree eki_shared: kemsk [private].\n\n"
    text += Walk(Role.INITIATOR, row.edits, row.breaks).emit(row.scenario)
    text += "\n\n"
    text += Walk(Role.RESPONDER, row.edits, row.breaks).emit(row.scenario)
    text += "\n\n"
    text += "\n".join(QUERIES[name] for name, _ in row.expects)
    text += "\n\n"
    text += MAINS[row.scenario]
    if not text.endswith("\n"):
        text += "\n"
    return text


def check_variants(rows: list[Row]) -> str | None:
    if not VARIANTS.is_dir():
        return f"{VARIANTS.name}/ is missing; run --write-variants and commit it"
    want = {f"{row.name}.pv" for row in rows}
    have = {path.name for path in VARIANTS.glob("*.pv")}
    if have != want:
        extra = ", ".join(sorted(have - want)) or "-"
        missing = ", ".join(sorted(want - have)) or "-"
        return f"variant set drifted: extra {extra}; missing {missing}"
    for row in rows:
        path = VARIANTS / f"{row.name}.pv"
        if path.read_text(encoding="utf-8") != render(row):
            return f"{path.name} is stale; run --write-variants and commit it"
    return None


def write_variants(rows: list[Row]) -> None:
    VARIANTS.mkdir(parents=True, exist_ok=True)
    keep = {f"{row.name}.pv" for row in rows}
    for row in rows:
        (VARIANTS / f"{row.name}.pv").write_text(render(row), encoding="utf-8")
    for path in VARIANTS.glob("*.pv"):
        if path.name not in keep:
            path.unlink()


