//! Published exit-seam KAT — cross-architecture bit-identical integer golden
//! vector for `draw_exit_gap` (F-D4 §9 step 2; Gate-6 §12.5 F-D3).
//!
//! Runs without the `conformance` feature (pure-integer only), so it rides the
//! aarch64 CI lane exactly as `golden_vector.rs` does for the entry draw. The
//! `exit-window-kat` dev-only feature supplies `ExitGapWindow::for_kat`; it
//! pulls no dependencies and no float, so the lane's integer-only guarantee is
//! unchanged.
//!
//! # Why the vector freezes at a KAT window, not the production const
//!
//! The entry vector freezes at `DEFAULT_ENTRY_GAP_WINDOW` so the certified and
//! operational windows cannot diverge. The exit window is a **provisional
//! sentinel `0`** (F-D4 §5.4) — a vector frozen there would be vacuous (all
//! zeros) and would certify nothing about the mechanism. So: the *mechanism*
//! vector below freezes at [`KAT_WINDOW`], a deliberately synthetic value, and
//! [`seal_tripwire_re_freeze_at_the_sealed_window`] fails loudly the moment
//! the sentinel is sealed — re-freezing the vector at the sealed window is
//! part of the seal procedure (`src/exit.rs` module docs), restoring the
//! entry-shaped single-sourcing from that point on.

mod common;

use common::SplitMix64;
use shekyl_standoff::{
    draw_exit_gap, ExitGapWindow, DEFAULT_EXIT_GAP_WINDOW, DEFAULT_EXIT_GAP_WINDOW_PROVISIONAL,
};

/// The reference gap stream's seed — same seed family as the entry vector.
const GOLDEN_SEED: u64 = 0xC0FF_EE12_3456_789A;

/// Mechanism-KAT window: **deliberately synthetic** — prime, not a
/// `SETTLEMENT_EPOCH_BLOCKS` multiple, and not a point in (or near) the F-D4
/// §5.1 planning box's candidate history — so the vector cannot be misread as
/// a window commitment (the F-W1 failure shape). It also does not divide
/// `2^64`, so the rejection-sampling path is exercised, not bypassed.
const KAT_WINDOW: u64 = 10_007;

/// First 16 gaps for `GOLDEN_SEED` / `KAT_WINDOW`. Generated by this crate's
/// reference draw; pinned so any change to the draw (or a non-bit-identical
/// architecture) is caught immediately.
const GOLDEN: [u64; 16] = [
    188, 972, 3895, 4383, 5839, 9680, 7686, 2044, 1477, 4246, 5531, 3051, 8441, 9276, 6302, 3794,
];

#[test]
fn exit_golden_vector_is_bit_identical() {
    let window = ExitGapWindow::for_kat(KAT_WINDOW);
    let mut rng = SplitMix64(GOLDEN_SEED);
    let seq: Vec<u64> = (0..GOLDEN.len())
        .map(|_| draw_exit_gap(window, &mut rng).blocks())
        .collect();
    assert_eq!(
        seq,
        GOLDEN.to_vec(),
        "exit golden vector drifted (draw changed or non-bit-identical arch)"
    );
}

#[test]
fn exit_draw_stays_within_window() {
    let window = ExitGapWindow::for_kat(KAT_WINDOW);
    let mut rng = SplitMix64(0x1234_5678_9ABC_DEF0);
    for _ in 0..100_000 {
        let gap = draw_exit_gap(window, &mut rng).blocks();
        assert!(gap <= KAT_WINDOW, "gap {gap} exceeded window {KAT_WINDOW}");
    }
}

#[test]
fn same_seed_reproduces_exit_sequence() {
    let window = ExitGapWindow::for_kat(KAT_WINDOW);
    let mut a = SplitMix64(GOLDEN_SEED);
    let mut b = SplitMix64(GOLDEN_SEED);
    for _ in 0..10_000 {
        assert_eq!(draw_exit_gap(window, &mut a), draw_exit_gap(window, &mut b));
    }
}

/// Pre-seal, the wallet-default draw is the degenerate zero gap — the
/// sentinel's runtime semantics, pinned executably (the shipping guard
/// against ever exercising this is the compile refusal in `src/exit.rs`,
/// never this value). **At the seal this test fails on its provisional
/// assertion by design**: the failure message is the instruction to re-freeze
/// this file's vector at the sealed window, restoring the entry-shaped
/// "certified window == operational window" single-sourcing.
#[test]
#[allow(clippy::assertions_on_constants)]
// ^ the assertion on a constant IS the mechanism: this test exists to fail at
//   the moment the seal edit flips `DEFAULT_EXIT_GAP_WINDOW_PROVISIONAL`, and
//   its failure message carries the re-freeze instruction. A const block
//   would forbid the interpolated sealed value in the message.
fn seal_tripwire_re_freeze_at_the_sealed_window() {
    assert!(
        DEFAULT_EXIT_GAP_WINDOW_PROVISIONAL,
        "DEFAULT_EXIT_GAP_WINDOW is sealed ({DEFAULT_EXIT_GAP_WINDOW}): re-freeze the exit \
         golden vector at the sealed window and re-point this test at it \
         (seal procedure, src/exit.rs module docs)"
    );
    let mut rng = SplitMix64(0xDEAD_BEEF_0000_0001);
    for _ in 0..1000 {
        assert_eq!(
            draw_exit_gap(ExitGapWindow::wallet_default(), &mut rng).blocks(),
            0,
            "provisional sentinel must draw the degenerate zero gap"
        );
    }
}
