//! Published KAT — cross-architecture bit-identical integer golden vector.
//!
//! Runs on **default features** (no `conformance`): it exercises only the
//! pure-integer [`draw_entry_gap`], so it compiles without the float grading
//! machinery and runs on the aarch64 CI lane to prove the `spread` sequence is
//! bit-identical across architectures. This is the part a wallet must reproduce
//! exactly; the float goodness-of-fit grading (`conformance_grading.rs`) is
//! graded by margin and stays x86-only.

mod common;

use common::SplitMix64;
use shekyl_standoff::draw::GapRng;
use shekyl_standoff::{
    bounded_uniform, draw_entry_gap, COVER_RUNG_ATOMIC, DEFAULT_ENTRY_GAP_WINDOW,
};

/// The reference `spread` stream for seed `0xC0FF_EE12_3456_789A` at the
/// canonical [`DEFAULT_ENTRY_GAP_WINDOW`] (600). Bit-identical on every
/// architecture (pure integer arithmetic, unbiased rejection sampling). If this
/// drifts, the draw changed. The window is sourced from the shared const (not a
/// bare literal) so the frozen reference and the wallet's operational window
/// cannot silently diverge: changing the const re-draws this vector and fails
/// the test until re-frozen (B6 single-source reconciliation, R0-D2).
const GOLDEN_SEED: u64 = 0xC0FF_EE12_3456_789A;
const GOLDEN_WINDOW: u64 = DEFAULT_ENTRY_GAP_WINDOW;

/// First 16 `spread` draws for `GOLDEN_SEED` / `GOLDEN_WINDOW`. Generated by
/// this crate's reference draw; pinned so any change to the draw (or a
/// non-bit-identical architecture) is caught immediately.
///
/// This vector was **re-frozen when the order coin was retired** (the draw
/// dropped from `(spread, bond_first)` to a bare `spread`). Its correctness is
/// not merely "the current code reproduces it" — that is circular on the commit
/// that freezes it. It is anchored to the *pre-retirement* golden stream by
/// [`draw_removed_exactly_the_coin_word`] below, which proves the only change to
/// the RNG consumption is the removal of the single coin word per draw.
const GOLDEN: [u64; 16] = [
    504, 362, 277, 141, 239, 118, 153, 229, 528, 438, 494, 38, 297, 288, 596, 152,
];

/// A `GapRng` that counts the `next_u64()` words drawn through it — the
/// instrument for the consumption-identity proof below.
struct Recording<R: GapRng> {
    inner: R,
    words: usize,
}
impl<R: GapRng> GapRng for Recording<R> {
    fn next_u64(&mut self) -> u64 {
        self.words += 1;
        self.inner.next_u64()
    }
}

#[test]
fn golden_vector_is_bit_identical() {
    let mut rng = SplitMix64(GOLDEN_SEED);
    let seq: Vec<u64> = (0..GOLDEN.len())
        .map(|_| draw_entry_gap(GOLDEN_WINDOW, &mut rng))
        .collect();
    assert_eq!(
        seq, GOLDEN,
        "standoff golden vector drifted (draw changed or non-bit-identical arch)"
    );
}

/// The retirement removed **exactly one RNG word per draw** — the coin, and no
/// residual. Two anchored facts, neither requiring the old implementation to be
/// kept around:
///
/// 1. **Consumption identity.** Post-retirement `draw_entry_gap(w, rng)`
///    consumes *exactly* the words `bounded_uniform(rng, w)` consumes and
///    returns the same value — proof there is no residual word (a leftover coin
///    draw would show as one extra `next_u64()`).
/// 2. **Continuity anchor.** The first golden spread is unchanged (`504`): the
///    coin was drawn *after* the spread, so removing it cannot move `spread[0]`.
///
/// Together these establish "exactly one word removed per draw" as a checked
/// property of the freezing commit, not an assumption.
#[test]
fn draw_removed_exactly_the_coin_word() {
    for w in [0u64, 1, 7, 600, GOLDEN_WINDOW, u64::MAX / 3] {
        let mut via_draw = Recording {
            inner: SplitMix64(GOLDEN_SEED),
            words: 0,
        };
        let mut via_prim = Recording {
            inner: SplitMix64(GOLDEN_SEED),
            words: 0,
        };
        let d = draw_entry_gap(w, &mut via_draw);
        let p = bounded_uniform(&mut via_prim, w);
        assert_eq!(
            d, p,
            "draw_entry_gap must equal bounded_uniform at window {w}"
        );
        assert_eq!(
            via_draw.words, via_prim.words,
            "draw_entry_gap consumed a word beyond bounded_uniform at window {w} \
             — a residual word means the coin was not fully removed"
        );
    }
    // Continuity anchor: the first spread is unchanged across the retirement.
    let mut rng = SplitMix64(GOLDEN_SEED);
    assert_eq!(draw_entry_gap(GOLDEN_WINDOW, &mut rng), 504);
    assert_eq!(GOLDEN[0], 504);
}

#[test]
fn draw_stays_within_window() {
    let mut rng = SplitMix64(0x1234_5678_9ABC_DEF0);
    for _ in 0..100_000 {
        let s = draw_entry_gap(GOLDEN_WINDOW, &mut rng);
        assert!(
            s <= GOLDEN_WINDOW,
            "spread {s} exceeded window {GOLDEN_WINDOW}"
        );
    }
}

#[test]
fn zero_window_draws_zero_spread() {
    let mut rng = SplitMix64(0xDEAD_BEEF_0000_0001);
    for _ in 0..1000 {
        let s = draw_entry_gap(0, &mut rng);
        assert_eq!(s, 0, "zero window must always draw spread 0");
    }
}

#[test]
fn same_seed_reproduces_sequence() {
    let mut a = SplitMix64(GOLDEN_SEED);
    let mut b = SplitMix64(GOLDEN_SEED);
    for _ in 0..10_000 {
        assert_eq!(
            draw_entry_gap(GOLDEN_WINDOW, &mut a),
            draw_entry_gap(GOLDEN_WINDOW, &mut b)
        );
    }
}

/// KAT for the shared unbiased sampler [`bounded_uniform`] at the **cover
/// scale**. The primitive survived the coin retirement — post-retirement
/// `draw_entry_gap` *is* `bounded_uniform(rng, window)` (so the window scale is
/// already pinned by [`GOLDEN`]) — and it also backs `draw_cover_amount`
/// (`cover`, `max = COVER_RUNG_ATOMIC - 2 ≈ 7.5e8`) and the WI-3 send-time
/// dispersal (`shekyl-engine-core::dispatch`), neither of which had a pinned
/// reference before. Pinning the large-`max` value exercises the wide
/// rejection-sampling path those callers use and anchors the shared root of all
/// three draws to a cross-architecture reference.
const BOUNDED_UNIFORM_COVER_KAT: [u64; 8] = [
    61175527, 682133600, 425744222, 374614954, 221763276, 536320935, 203582948, 84799938,
];

#[test]
fn bounded_uniform_cover_scale_is_pinned() {
    let max = COVER_RUNG_ATOMIC - 2;
    let mut rng = SplitMix64(GOLDEN_SEED);
    let seq: Vec<u64> = (0..BOUNDED_UNIFORM_COVER_KAT.len())
        .map(|_| bounded_uniform(&mut rng, max))
        .collect();
    assert_eq!(
        seq, BOUNDED_UNIFORM_COVER_KAT,
        "bounded_uniform drifted at the cover scale (draw_cover_amount / WI-3 \
         dispersal share this primitive)"
    );
    for &v in &seq {
        assert!(v <= max, "bounded_uniform exceeded max");
    }
}
