//! Published KAT — cross-architecture bit-identical integer golden vector.
//!
//! Runs on **default features** (no `conformance`): it exercises only the
//! pure-integer [`draw_entry_gap`], so it compiles without the float grading
//! machinery and runs on the aarch64 CI lane to prove the `(spread, bond_first)`
//! sequence is bit-identical across architectures. This is the part a wallet
//! must reproduce exactly; the float goodness-of-fit grading
//! (`conformance_grading.rs`) is graded by margin and stays x86-only.

mod common;

use common::SplitMix64;
use shekyl_standoff::{draw_entry_gap, DEFAULT_ENTRY_GAP_WINDOW};

/// The reference `(spread, bond_first)` stream for seed `0xC0FF_EE12_3456_789A`
/// at the canonical [`DEFAULT_ENTRY_GAP_WINDOW`] (600). Bit-identical on every
/// architecture (pure integer arithmetic, unbiased rejection sampling). If this
/// drifts, the draw changed. The window is sourced from the shared const (not a
/// bare literal) so the frozen reference and the wallet's operational window
/// cannot silently diverge: changing the const re-draws this vector and fails
/// the test until re-frozen (B6 single-source reconciliation, R0-D2).
const GOLDEN_SEED: u64 = 0xC0FF_EE12_3456_789A;
const GOLDEN_WINDOW: u64 = DEFAULT_ENTRY_GAP_WINDOW;

/// First 16 `(spread, bond_first)` draws for `GOLDEN_SEED` / `GOLDEN_WINDOW`.
/// Generated by this crate's reference draw; pinned so any change to the draw
/// (or a non-bit-identical architecture) is caught immediately.
const GOLDEN: [(u64, bool); 16] = [
    (504, false),
    (277, true),
    (239, false),
    (153, false),
    (528, false),
    (494, true),
    (297, false),
    (596, false),
    (524, true),
    (437, true),
    (409, false),
    (407, false),
    (571, false),
    (583, false),
    (266, false),
    (32, true),
];

#[test]
fn golden_vector_is_bit_identical() {
    let mut rng = SplitMix64(GOLDEN_SEED);
    let seq: Vec<(u64, bool)> = (0..GOLDEN.len())
        .map(|_| draw_entry_gap(GOLDEN_WINDOW, &mut rng))
        .collect();
    assert_eq!(
        seq, GOLDEN,
        "standoff golden vector drifted (draw changed or non-bit-identical arch)"
    );
}

#[test]
fn draw_stays_within_window() {
    let mut rng = SplitMix64(0x1234_5678_9ABC_DEF0);
    for _ in 0..100_000 {
        let (s, _) = draw_entry_gap(GOLDEN_WINDOW, &mut rng);
        assert!(
            s <= GOLDEN_WINDOW,
            "spread {s} exceeded window {GOLDEN_WINDOW}"
        );
    }
}

#[test]
fn zero_window_draws_zero_spread() {
    let mut rng = SplitMix64(0xDEAD_BEEF_0000_0001);
    for _ in 0..1000 {
        let (s, _) = draw_entry_gap(0, &mut rng);
        assert_eq!(s, 0, "zero window must always draw spread 0");
    }
}

#[test]
fn same_seed_reproduces_sequence() {
    let mut a = SplitMix64(GOLDEN_SEED);
    let mut b = SplitMix64(GOLDEN_SEED);
    for _ in 0..10_000 {
        assert_eq!(
            draw_entry_gap(GOLDEN_WINDOW, &mut a),
            draw_entry_gap(GOLDEN_WINDOW, &mut b)
        );
    }
}
